### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by o9000** [johanmalm/jgmenu#1]
Linking fails on Ubuntu with a lot of unresolved symbols.

This is because link flags should occur after objects, not before, in the arguments, as by default the linker purges all unused symbols as it processes parameters from left to right. I suppose it works on your system because you have the flag Wl,--start-group set or something similar.

Fix:

```diff
diff --git a/Makefile b/Makefile
index 88b71ca..e5f5932 100644
--- a/Makefile
+++ b/Makefile
@@ -22,7 +22,7 @@ all: $(PROGS) $(OBJS)
 
 jgmenu: jgmenu.c $(OBJS)
        @echo $(CC) $@
-       @$(CC) $(LDFLAGS) $(CFLAGS) -o jgmenu $(OBJS) jgmenu.c
+       @$(CC) $(CFLAGS) -o jgmenu $(OBJS) jgmenu.c $(LDFLAGS)
 
 x11-ui.o: x11-ui.c x11-ui.h
        @echo $(CC) $@
```

Reference: https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html "It makes a difference where in the command you write this option..."

**Comment by johanmalm** [comment]
Thanks. Helpful.
