### ISSUE TITLE
cppcheck +=       --library=gnu

### ISSUE THREAD

**Issue by opk12** [johanmalm/jgmenu#101]
where gnu is resolved to /usr/share/cppcheck/cfg/gnu.cfg.

Nothing else in /usr/share/cppcheck/cfg/ seems to apply.

**Comment by johanmalm** [comment]
I've tried running with this, but don't get any additional warnings. I'll leave it in for good measure though.
I don't think I use any gnu extensions except a couple in list.h - which would be tricky to get rid of.

**Comment by johanmalm** [comment]
1.
