### ISSUE TITLE
scripts/find-banned-functions.sh: consider gcc-poison

### ISSUE THREAD

**Issue by opk12** [johanmalm/jgmenu#102]
A preprocessor-based detector of banned functions. <https://github.com/leafsr/gcc-poison>

**Comment by johanmalm** [comment]
Thanks. I will implement something like this.

**Comment by johanmalm** [comment]
Sorry - forgot to reference the issue in the commit message.
https://github.com/johanmalm/jgmenu/blob/master/src/banned.h
