### ISSUE TITLE
Option to adjust last selection border

### ISSUE THREAD

**Issue by Roliga** [johanmalm/jgmenu#103]
Hi! I think it would be nice to be able to adjust/disable the "last selection" border.

It looks like the border width is hardcoded now:
https://github.com/johanmalm/jgmenu/blob/56459f3fa4696b01b078323d8592697bdf2ffa1b/src/jgmenu.c#L510-L517

Either it could have its own option for its width, simply whether it should be drawn at all or not, or maybe it could just follow the `item_border` option.

Or maybe it'd even make sense to just do exactly the same as the border for the selected item  and change it to follow both the `item_border` and `color_sel_border` options:
https://github.com/johanmalm/jgmenu/blob/56459f3fa4696b01b078323d8592697bdf2ffa1b/src/jgmenu.c#L533-L535

What do you think, is any of this a good idea? (:

**Comment by johanmalm** [comment]
Yes, good idea. I'll add some config options to control this.

**Comment by johanmalm** [comment]
Decided to just hide it :) as I don’t think that anyone would actually want to see it.

**Comment by Roliga** [comment]
Looks great! Thank you so much!
