### ISSUE TITLE
virt-manager does not appear in lx applications menu

### ISSUE THREAD

**Issue by johnraff** [johanmalm/jgmenu#105]
Using **jgmenu 3.5+bl9-1** on Bunsenlabs, Debian Stretch, with a prepend.csv almost identical with BunsenLabs Lithium version: https://github.com/BunsenLabs/bunsen-configs/blob/lithium/skel/.config/jgmenu/prepend.csv

With **virt-manager 1:1.4.0-5** installed, _/usr/share/applications/virt-manager.desktop_ exists (content below) but the entry (expected "Virtual Machine Manager" under "Applications">"System") does not apear anywhere in the menu. 

Content of .desktop file:
```
[Desktop Entry]
Name=Virtual Machine Manager
Name[as]=ভাৰ্চুৱেল ডিভাইচ ব্যৱস্থাপক
Name[bg]=Мениджър на виртуални машини
Name[bn_IN]=ভার্চুয়াল মেশিন ম্যানেজার
Name[bs]=Upravljač virtualnog računala
Name[ca]=Eina de gestió de màquines virtuals
Name[cs]=Správce virtuálních strojů
Name[da]=Administration for virtuel maskine
Name[de]=Virtuelle Maschinenverwaltung
Name[en_GB]=Virtual Machine Manager
Name[es]=Gestor de máquinas virtuales
Name[fi]=Virtuaalikoneiden hallitsin
Name[fr]=Gestionnaire de machine virtuelle
Name[gu]=વર્ચ્યુઅલ મશીન વ્યવસ્થાપક
Name[hi]=वर्चुअल मशीन प्रबंधक
Name[hr]=Upravljač virtualnog računala
Name[hu]=Virtuális Gép vezérlőpult
Name[it]=Virtual Machine Manager
Name[ja]=仮想マシンマネージャー
Name[kn]=ವರ್ಚುವಲ್‌ ಗಣಕ ವ್ಯವಸ್ಥಾಪಕ
Name[ko]=가상 머신 관리자
Name[ml]=വിര്‍ച്ച്വല്‍ മഷീന്‍ മാനേജര്‍
Name[mr]=वर्च्युअल मशीन व्यवस्थापक
Name[ms]=Pengurus Mesin Maya
Name[nl]=Virtuele machine beheerder
Name[or]=ଆଭାସୀ ମେସିନ ପରିଚାଳକ
Name[pa]=ਵਰਚੁਅਲ ਮਸ਼ੀਨ ਮੈਨੇਜਰ
Name[pl]=Menedżer maszyn wirtualnych
Name[pt]=Gestor de Máquinas Virtuais
Name[pt_BR]=Gerenciador de Máquinas Virtuais
Name[ro]=Manager maşină virtuală
Name[ru]=Менеджер виртуальных машин
Name[sk]=Správca virtuálnych počítačov
Name[sr]=Управник виртуелне машине
Name[sr@latin]=Upravnik virtuelne mašine
Name[sv]=Administrerare av virtuella maskiner
Name[ta]=மெய்நிகர் கணினி மேலாளர்
Name[te]=వర్చ్యువల్ కంప్యూటరు నిర్వహణాధికారి
Name[tr]=Sanal Makine Yöneticisi
Name[uk]=Інструмент керування віртуальними машинами
Name[zh_CN]=虚拟系统管理器
Name[zh_TW]=虛擬機管理員
Comment=Manage virtual machines
Icon=virt-manager
Exec=virt-manager
Type=Application
Terminal=false
Categories=System;
```

**Comment by johanmalm** [comment]
Thanks for raising.
Does it appear if you restart jgmenu (press F5)
Does it appear if you delete the lx cache and the restart jgmenu (~/.cache/menu-data I think off the top of my head)
Does it appear if you set csv_cmd=pmenu

**Comment by johnraff** [comment]
_Does it appear if you restart jgmenu (press F5_) - No
_Does it appear if you delete the lx cache_ - There is no ~/.cache/jgmenu directory, or any other likely-looking directory.
_Does it appear if you set csv_cmd=pmenu_ - Ah this might be a hint, lx is not supported on Debian Stretch, and I am already using pmenu.

**Comment by johanmalm** [comment]
I've tried creating a **/usr/share/applications/virt-manager.desktop** and it appears quite nicely on mine :smile:
![2019-11-07-214433_1920x1080_scrot](https://user-images.githubusercontent.com/6955353/68430548-28458680-01a8-11ea-9019-3b1a08e1d537.png)

Could you try `jgmenu_run pmenu` and then grep for 'Virtual' or something.

Have you got another `virt-manager.desktop` in `~/.local/share/applications/`?

Have you set your XDG_DATA_* environment variables to anything unusual?

If none of the above give you a clue, what output do you get with `jgmenu_run apps | grep 'Virt'`?

**Comment by johnraff** [comment]
> Have you got another `virt-manager.desktop` in `~/.local/share/applications/`?

That was it. I had edited the Categories so it would appear under "Virtualization" along with Virtualboxbox, so this:
```
[Desktop Entry]
Name=Virtual Machine Manager
Comment=Manage virtual machines
Icon=virt-manager
Exec=virt-manager
Type=Emulator;System;X-MandrivaLinux-System;Application;
Terminal=false
Categories=Emulator;System;X-MandrivaLinux-System;Application;
```
If I move it out of ~/.local/share/applications/ then the menu item appears in jgmenu, under System. But in my gnome-menu based menu it has thus moved to "System", and I wanted it under "Virtualization". 

And I now see the problem. Type should be 'Type=Application`. It seems jgmenu is a little less tolerant of badly formatted .desktop files than my other menu (ADeskBar), but that's OK.

Sorry for the noise.
