### ISSUE TITLE
[not a issue] keyboard shortcuts reminder appearance in menus descriptions

### ISSUE THREAD

**Issue by paoloschi** [johanmalm/jgmenu#107]
I'm defining a jgmenu where it becomes useful to present the reminder of shortcuts that produce the same action of the corresponding menu items.
It's a very common scenario in all application menus but I guess it's a gtk/kde thing…
I tried to imitate the effect "_portion of the description string aligned to the right, with reduced appariscence_" by dealing with pango markup and some `\t` controls but with very approximate results (...)
It would take in practice the possibility of aligning a sub-string of the description all on the right (where the arrows indicating the sub-menus appear) or maybe an additional, optional element separated by comma in definitions syntax  
??

(if it's a functionality already introduced/planned I apologize for not having found so far a reference...)

**Comment by johanmalm** [comment]
![2019-12-20-200651_1920x1080_scrot](https://user-images.githubusercontent.com/6955353/71289214-77183b80-2364-11ea-9ab2-705c2b844630.png)

Use `tabs` in jgmenurc to specify tab position. E.g. `tabs = 80`

In the above screenshot, I did the following

```
one	alpha
two	beta
three	gamma
```

Using a tab character between one and alpha, etc.

**Comment by johanmalm** [comment]
I'll close for now. Let me know if I misunderstood the question.
