### ISSUE TITLE
Menu appears on wrong monitor

### ISSUE THREAD

**Issue by atmenta** [johanmalm/jgmenu#108]
First of all, thank you for jgmenu!

When config contains `position_mode = ipc`, `monitor = 0`, and `stay_alive = 1`, and jgmenu is launched by a Tint2 Button the menu always appears on the monitor where it was launched first time, regardless on which monitor the Tint2 Button was pressed. (The expected behavior would be to appear an that monitor where the the Tint2 Button was pressed.)

In the case when jgmenu appears on a wrong monitor the "pointer outside IPC varable range" is displayed on the stdout. If `verbosity = 4` is set in the config file, it seems that the monitor's coordinates are determined only on startup. This explains that error message for me.

As a quick fix I modified the code of `src/ipc.c` by calling `geo_update_monitor_coords` at the beginning of `align_to_horizontal_panel` and `align_to_vertical_panel`. This seems to fix the bug for me. However, I don't really know jgmenu's internals an I am not a C programmer, so you may find a better fix.

**Comment by johanmalm** [comment]
Thanks. I’ll take a look.

**Comment by johanmalm** [comment]
Thanks for providing a solution :)
Would have taken me a while.
Might refactor later.
