### ISSUE TITLE
Wrong libdir for x64

### ISSUE THREAD

**Issue by tieugene** [johanmalm/jgmenu#109]
By default it installs "plugins" into /usr/lib/... (in x64 environment) instead of right /usr/lib64/...
BTW (Fedora 31 x64):
--libdir=/usr/lib64 --libexecdir=/usr/libexec

**Comment by johanmalm** [comment]
Thanks. Great feedback.

**Comment by johnraff** [comment]
On a Debian system there is no /usr/lib64 directory.
I think the usual path in that case would be /usr/lib/x86_64-linux-gnu/...
