### ISSUE TITLE
Xfce4 plugin: too debian path

### ISSUE THREAD

**Issue by tieugene** [johanmalm/jgmenu#110]
contrib/xfce4-panel/Makefile:
> ifeq ($(shell dpkg-architecture -q DEB_HOST_ARCH 2>/dev/null),i386)
> LIBDIR     = $(DESTDIR)$(prefix)/lib/i386-linux-gnu/xfce4/...
> ...

Fedora:
x32 - /usr/lib/xfce4/...
x64 - /usr/lib64/xfce4/...

Solution:
> LIBDIR     = $(DESTDIR)\`pkg-config --variable=libdir libxfce4panel-1.0\`/xfce4/panel/plugins

**Comment by johanmalm** [comment]
Thanks. Will implement.
