### ISSUE TITLE
The menu will not launch

### ISSUE THREAD

**Issue by dcote007** [johanmalm/jgmenu#112]
Hello, I am trying to get the jgmenu to launch, however it does not seem to want to create the window no matter what I do.

Details:
Ubuntu Focal (20.04)
Desktop: i3

Whenever I run "jgmenu_run" it gives me this error:
Segmentation fault (core dumped)
fatal: file did not contain any menu items

However when I run "jgmenu_run pmenu", I get a long list of menu items.

If I run: "jgmenu_run >/dev/null 2>&1 &" then I get:
[1] 28044 
Where 28044 is the PID, but no window appears or pops up anywhere.

I have seen screenshots of your menu and would really like to use it, but I need some help here, any assistance would be greatly appreciated, thank you!

**Comment by johanmalm** [comment]
Hi
What version of jgmenu are you using?
The default csv_cmd value is “apps” since v4.0
Could you run the following and post output.

    jgmenu_run apps

Are you happy to build from scratch?

**Comment by dcote007** [comment]
I am unsure of the version, as i just git cloned the most recent version (within these past 4 days) and built it from source.

I ran 
"jgmenu_run apps"
and got the following result:
"Segmentation fault (core dumped)"
That's it, no additional output.

Also, like I mentioned this is built from scratch from using the make and build commands.

**Comment by dcote007** [comment]
So I looked up the error I got and saw that the problem may have been that the program didn't have access to some memory, okay fine so I ran sudo jgmenu_run, and got the following result:

warning: set font to 'Sans 11' because all else failed
Segmentation fault (core dumped)
fatal: file did not contain any menu items

**Comment by johanmalm** [comment]
Okay. No need to run with sudo.
The issue is with the ‘apps’ module.
Could you try the following and post the output:

    make clean
    ./configure --enable-asan
    make
    ./jgmenu-apps

**Comment by dcote007** [comment]
So I did this and here is the output:

`==19123==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55d760500801 bp 0x7fffc4e84130 sp 0x7fffc4e84110 T0)
==19123==The signal is caused by a READ memory access.
==19123==Hint: address points to the zero page.
    #0 0x55d760500800 in strip_exec_field_codes src/util.c:320
    #1 0x55d7605038fc in add_app src/desktop.c:145
    #2 0x55d760503b8b in process_file src/desktop.c:170
    #3 0x55d760503cf0 in traverse_directory src/desktop.c:189
    #4 0x55d760504042 in desktop_read_files src/desktop.c:221
    #5 0x55d7604fe1c9 in main src/jgmenu-apps.c:229
    #6 0x7fa6640361e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #7 0x55d7604fc84d in _start (/home/user/jgmenu/jgmenu-apps+0x1784d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/util.c:320 in strip_exec_field_codes
==19123==ABORTING`

**Comment by johanmalm** [comment]
Ok. Thanks, I can see what’s going on. Can’t get to computer for a few days. Could you checkout v4.0.2 for the time being.

    make clean
    git checkout v4.0.2
    make

**Comment by dcote007** [comment]
Okay, I'm glad you see whats happening, I got version 4.0.2 to work, so I'm happy lol. Thanks for all your help and Jgmenu of course!

**Comment by johanmalm** [comment]
Done. Thanks for your help identifying the bug
