### ISSUE TITLE
Inconsistent filepaths in jgmenu script args

### ISSUE THREAD

**Issue by capn-damo** [johanmalm/jgmenu#113]
``--config-file`` can use ``~/`` for the user's $HOME, but ``--csv-file=`` requires the full file path:

``jgmenu --simple --csv-file='/home/damo/.config/jgmenu/my-menu.csv'  
--config-file='~/.config/jgmenu/my-jgmenurc'``

It would be nice if the short ``~/`` was universal.

**Comment by johanmalm** [comment]
Thanks Damo. Good pick-up. I’ll sort that out.

**Comment by johanmalm** [comment]
Done
