### ISSUE TITLE
rocket icon

### ISSUE THREAD

**Issue by InvisibleRasta** [johanmalm/jgmenu#117]
hello, is the rocket icon hardcoded ? i cant find any information on how to change it

**Comment by johanmalm** [comment]
Hi
The icon is not hard-coded.
The icon and .desktop files are in [data/](https://github.com/johanmalm/jgmenu/tree/master/data)
Depending on what distribution you use they'll be installed somewhere like:
/usr/share/icons/hicolor/scalable/apps/
/usr/share/applications/
I'm guessing the application/panel/etc that your using is reading the .desktop file. If this is the case, you can create your own copy in ~/.local/share/applications/ and change the icon (and anything else) to suit.

**Comment by InvisibleRasta** [comment]
i am using archlinux and i installed jgmenu from official repos community/jgmenu 4.1.0-1

**Comment by InvisibleRasta** [comment]
i made this entry in /home/invra/.local/share/applications/jgmenu.desktop  downlaoded a png file i want as icon and palced it in the same directory as jgmenu. But still after restarting tint2 and jgmenu the icon remains the same

[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=jgmenu
GenericName=Application Menu
Comment=Displays menu for launching installed applications
Exec=jgmenu_run
Terminal=false
Icon=/home/invra/.local/share/applications/jgmenu
Categories=System
StartupNotify=false

**Comment by johanmalm** [comment]
In your jgmenu.desktop file above, should it be jgmenu.png at the end of the "Icon" value?
You'd normally put icons under ~/.local/share/icons/ - but as you'respecifying an absolute path, it doesn't really matter.

There are different way of creating a button/launcher/icon in tint2.
I'm assuming that you you're using the launcher plugin (L).

The preferred method for jgmenu is to use a button (P).
If you go to [jgmenu.github.io](https://jgmenu.github.io/) and click on integration, there are more details on how to use a tint2 button

**Comment by johanmalm** [comment]
I’ll close this. Let me know if you need more help with tint2.
