### ISSUE TITLE
apps module does not print applications (Archlabs jgmenu-4-2-0-1)

### ISSUE THREAD

**Issue by geolaw** [johanmalm/jgmenu#119]
Opening an issue here just for visibility.
I've also got it opened on the arch labs website :
https://forum.archlabslinux.com/t/jgmenu-broken-since-latest-updates-jgmenu-4-2-0-1/4546/7

So if I back it down to the previous version the menu works via polybar 
as soon as I upgrade, i just get the spacing around where the normal menu is
the only options I have in my config is the spacing and color
$ cat jgmenurc|grep -v ^#
menu_margin_x = 30
menu_margin_y = 25
menu_valign = top
color_menu_bg = #000000 80

I downgrade back to the previous version and everything works fine.
# sudo pacman -U /var/cache/pacman/pkg/jgmenu-4.1.0-1-x86_64.pkg.tar.zst

I also tried cloning from github and installing over the arch linux package (configure with --prefix=/usr) but still get the same issue.

**Comment by johanmalm** [comment]
Have responded on the forum.
Output of 

    jgmenu_run apps

Would be useful.

**Comment by geolaw** [comment]
italicized ones are my .csv prepend/append 

_Terminal,terminator,utilities-terminal
Firefox,firefox,firefox
Chromium,chromium,chromium
File manager,caja,system-file-manager
Geany,geany,geany
GiMP,gimp,gimp_

Accessories,^checkout(apps-dir-Accessories),applications-accessories
Development,^checkout(apps-dir-Development),applications-development
Education,^checkout(apps-dir-Education),applications-science
Games,^checkout(apps-dir-Games),applications-games
Graphics,^checkout(apps-dir-Graphics),applications-graphics
Multimedia,^checkout(apps-dir-Multimedia),applications-multimedia
Internet,^checkout(apps-dir-Internet),applications-internet
Office,^checkout(apps-dir-Office),applications-office
Other,^checkout(apps-dir-Other),applications-other
Settings,^checkout(apps-dir-Settings),preferences-desktop
System,^checkout(apps-dir-System),applications-system
_Exit to prompt,openbox --exit,system-log-out
Suspend,systemctl -i suspend,system-log-out
Reboot,systemctl -i reboot,system-reboot
Poweroff,systemctl -i poweroff,system-shutdown_

I've got a few .desktop files in ~/.local/share/applications - but just things like wine and stuff -

rw-------  1 glaw users  296 Apr 21 15:50 chrome-fahmaaghhglfmonjliepjlchgpgfmobi-Default.desktop
-rw-------  1 glaw users  300 Dec 26 14:34 chrome-icklgohmolmmdagbigdkhhcgdechbeje-Default.desktop
-rw-r--r--  1 glaw users  752 Apr 21 15:50 mimeinfo.cache
-rw-r--r--  1 glaw users  139 Dec 23 15:31 userapp-picard-RBQLD0.desktop
drwxr-xr-x  3 glaw users 4096 Jan 10 16:32 wine/
-rw-r--r--  1 glaw users  202 Jan 10 16:31 wine-extension-chm.desktop
-rw-r--r--  1 glaw users  209 Jan 10 16:31 wine-extension-gif.desktop
-rw-r--r--  1 glaw users  204 Jan 10 16:31 wine-extension-hlp.desktop
-rw-r--r--  1 glaw users  202 Jan 10 16:31 wine-extension-htm.desktop
-rw-r--r--  1 glaw users  216 Jan 10 16:31 wine-extension-ini.desktop
-rw-r--r--  1 glaw users  212 Jan 10 16:31 wine-extension-jfif.desktop
-rw-r--r--  1 glaw users  211 Jan 10 16:31 wine-extension-jpe.desktop
-rw-r--r--  1 glaw users  225 Jan 10 16:31 wine-extension-msp.desktop
-rw-r--r--  1 glaw users  207 Jan 10 16:31 wine-extension-pdf.desktop
-rw-r--r--  1 glaw users  209 Jan 10 16:31 wine-extension-png.desktop
-rw-r--r--  1 glaw users  199 Jan 10 16:31 wine-extension-rtf.desktop
-rw-r--r--  1 glaw users  194 Jan 10 16:31 wine-extension-txt.desktop
-rw-r--r--  1 glaw users  217 Jan 10 16:31 wine-extension-url.desktop
-rw-r--r--  1 glaw users  207 Jan 10 16:31 wine-extension-vbs.desktop
-rw-r--r--  1 glaw users  205 Jan 10 16:31 wine-extension-wri.desktop
-rw-r--r--  1 glaw users  207 Jan 10 16:31 wine-extension-xml.desktop

I've temporarily renamed this directory but no affect - without the config option 'csv_cmd =pmenu' I still just get my prepend/append menu items

**Comment by johanmalm** [comment]
Would you be able to try now?

**Comment by johanmalm** [comment]
The best way to test is:

    git clone https://github.com/johanmalm/jgmenu.git
    cd jgmenu
    ./configure
    make
    ./jgmenu-apps

Then paste the output.
No need to install or anything else.

**Comment by johanmalm** [comment]
If you haven't already got them installed, you would need to install make, gcc and pkg-config

**Comment by johanmalm** [comment]
Could you paste one of the wine .desktop files, so I can see how they are structured.

**Comment by geolaw** [comment]
So I had done a git clone yesterday when I was initially testing.
so i just did a pull  and looks like I got the latest updates : 
From https://github.com/johanmalm/jgmenu
   64f63f1..1b58ffd  master     -> origin/master
Updating 64f63f1..1b58ffd
Fast-forward
 scripts/pbuild    | 10 ++++++++--
 src/desktop.c     |  4 +++-
 src/desktop.h     |  1 +
 src/jgmenu-apps.c |  6 +++---
 4 files changed, 15 insertions(+), 6 deletions(-)

Before I read your update I had already done a 
make clean
./configure --prefix=/usr
make 
sudo make install

I commended the #csv_cmd =pmenu out in the rc file and then pkill jgmenu
Looks good.

Then I see your update and here is the output from jgmenu-apps

[jgmenu-apps_output.txt](https://github.com/johanmalm/jgmenu/files/4652733/jgmenu-apps_output.txt)

And then here is my .local/share/applications and all of its desktop files

[applications.zip](https://github.com/johanmalm/jgmenu/files/4652749/applications.zip)

**Comment by johanmalm** [comment]
Thanks for getting back so quickly. That's all looking good.
I've up-versioned to v4.2.1
Thanks for the help.
