### ISSUE TITLE
jgmenu is not exit-able by clicking after clicking multiple times on launcher

### ISSUE THREAD

**Issue by kilbith** [johanmalm/jgmenu#12]
Click multiple times (like 10-15 times) very quickly on the launcher that starts `jgmenu`, then `jgmenu` is "stuck" and the only way to quit it is to press <kbd>Esc</kbd>.

**Comment by johanmalm** [comment]
Thanks for the feedback.
I'll try to re-create tonight.
Where are you launching from? (tint2?)
When it happens, have you got 2 jgmenu processes running?

**Comment by kilbith** [comment]
Starting from a `tint2`'s launcher.

I see two processes when `jgmenu` is running : `jgmenu` and `/usr/lib/jgmenu/jgmenu-pmenu.sh`

**Comment by johanmalm** [comment]
I'm not able to re-produce this behaviour.
I've tried [code](jgmenu_run pmenu & jgmenu_run pmenu)[/code] but the wrapper around XGrabKeyboard() prevents the second one from starting.
I could wrap XGrabPointer() in the same way.

**Comment by johanmalm** [comment]
The same thing happened to me this morning.
I did the following at the same time
  - updaing system
  - compiling
  - calling jgmenu using a keyboard shortcut
  - calling jgmenu using a tint2 launcher
I've pushed a fix.
