### ISSUE TITLE
lockdown

### ISSUE THREAD

**Issue by pavroo** [johanmalm/jgmenu#120]
Hi
I debianize jgmenu for Sparky (Debian based), and it works fine up to 4.1.0.
The latest 4.2.1 starts ones, and then the lockdown file doesn't let to start it again.
pavroo

**Comment by johanmalm** [comment]
Try starting with jgmenu_run

You’re only meant to be able to run one instance in “long running” mode.

**Comment by pavroo** [comment]
ok, thanks.
