### ISSUE TITLE
Icon themes which symlink to other themes don't work

### ISSUE THREAD

**Issue by rafern** [johanmalm/jgmenu#122]
Icon themes like Papirus-Dark don't work properly. I think its because Papirus-Dark only updates symbolic icons that use a single color, from dark grey to white, and all other icons are symlinked to the original Papirus theme. I don't think its a problem with Papirus as this behavior only occurs in jgmenu, probably because of icon caching

With Papirus-Dark, notice only the symbolic icons are changed, when it should also use the original Papirus icons for all other icons:
![2020-05-28_13-33](https://user-images.githubusercontent.com/15365765/83142815-eac72d00-a0e8-11ea-8495-8a15fbae44b8.png)

With Papirus, it works as expected, with dark grey symbolic icons (which don't match the theme, hence why I want to use Papirus-Dark):
![2020-05-28_13-34](https://user-images.githubusercontent.com/15365765/83142620-a89deb80-a0e8-11ea-9f4e-265c764493c1.png)

.jgmenu contents (only changed settings):
```
csv_cmd = pmenu
tint2_look = 1
font = Noto Sans 10
icon_size = 16
csv_no_duplicates = 1
```

I don't think it relates, but the icon theme was supplied by xsettingsd. .xsettingsd contents:
```
Net/IconThemeName "Papirus-Dark"
Net/ThemeName "Arc-Dark"
```
</details>

**Comment by johanmalm** [comment]
Thanks. I'll have a look.

**Comment by undefinedDarkness** [comment]
Any luck on this, it still doesnt seem to work

**Comment by VectorKappa** [comment]
It's even worse in my case; when setting the icon theme to Papirus-Dark, the symlinks in `~/.cache/jgmenu/icons` all point to the hicolor icon pack (default set in icons.c) or `/usr/share/pixmaps` in some cases, sometimes even borked symlinks that point to themselves, which results in just a few icons displayed.

In just Papirus, everything works, albeit some icons are darker in colour, which makes them invisible. I'll provide some screenshots here:

# Papirus-Dark
## jgmenu appearance
![190](https://user-images.githubusercontent.com/29167842/141090390-ca7e9bae-347a-465f-999a-a8340aa3aedc.png)

## Cache folder contents
![image](https://user-images.githubusercontent.com/29167842/141090997-78555146-8ca3-4de5-b5bf-1f6e3bb2b889.png)

# Papirus
## jgmenu appearance
![950](https://user-images.githubusercontent.com/29167842/141091304-b1d8edb9-5939-4942-bd15-577b8efc3c1d.png)

## Cache folder contents
![image](https://user-images.githubusercontent.com/29167842/141091605-00417211-b369-45a1-83b5-8f734f33d71a.png)

---

# Both Icon Packs' folders' contents
![image](https://user-images.githubusercontent.com/29167842/141093322-2b0d07f4-acd7-47cc-8c25-c99e10b3148d.png)

---

I'll try to analyze the code, symlink traversal must be broken.

**Comment by M4he** [comment]
I think I might've found the source of the issue.

If you look at the "Papirus-Dark" icon theme directory:

```
/usr/share/icons/Papirus-Dark
├── 128x128 -> ../Papirus/128x128
├── 16x16
├── 16x16@2x -> 16x16
├── 18x18
├── 18x18@2x -> 18x18
├── 22x22
├── 22x22@2x -> 22x22
├── 24x24
├── 24x24@2x -> 24x24
├── 32x32 -> ../Papirus/32x32
...
├── index.theme
└── symbolic
```
... you can see that even top-level directories in the theme themselves are symbolic links.

Now in the code of `jgmenu`, it tries to inspect each main directory of available icon themes beginning with the configured one and then going on with its `Inherits=` chain (e.g. `/usr/share/icons/Papirus-Dark/`, then `/usr/share/icons/breeze-dark/` and so on). During this inspection, it looks at each entry in the icon theme's main directory and evaluates its type.

If it is a genuine directory (i.e. subdirectory in the icon theme), it will further traverse into the directory to look for matching icons:

https://github.com/johanmalm/jgmenu/blob/58fde284040dbbae334b4502e4f33084c0a192fc/src/icon-find.c#L269-L271

If it is either a **symbolic link** or a regular file, it will treat it as an icon and check if it matches any of the wanted icons:

https://github.com/johanmalm/jgmenu/blob/58fde284040dbbae334b4502e4f33084c0a192fc/src/icon-find.c#L272-L276

Now, if you look at "Papirus-Dark" again:

```

/usr/share/icons/Papirus-Dark
...
├── 32x32 -> ../Papirus/32x32
...
```
The "32x32" subdirectory is actually a symbolic link. This means in the code its type is `DT_LNK` not `DT_DIR`. This in turn leads to `if (entry->d_type == DT_DIR)` failing and the code will not treat it as a directory and skip traversing its contents. It does trigger `else if (entry->d_type == DT_REG || entry->d_type == DT_LNK)` but that part only checks for icon files with matching names of on jgmenu's "wanted" list.

This is a blind spot: an icon theme's subdirectory which is simultaneously a symbolic link itself is not considered by the code for inspection/traversal.

It seems to work for me if I hack the code to also try treating the entry as a directory if it is a symbolic link:

```diff
diff --git a/src/icon-find.c b/src/icon-find.c
index 1c36230..d59df85 100644
--- a/src/icon-find.c
+++ b/src/icon-find.c
@@ -270,6 +270,9 @@ static void search_dir_for_files(const char *path, struct list_head *files, int
                        if (entry->d_name[0] != '.')
                                search_dir_for_files(s.buf, files, depth_limit > 0 ? depth_limit - 1 : depth_limit);
                } else if (entry->d_type == DT_REG || entry->d_type == DT_LNK) {
+                       if (entry->d_type == DT_LNK)
+                               if (entry->d_name[0] != '.')
+                                       search_dir_for_files(s.buf, files, depth_limit > 0 ? depth_limit - 1 : depth_limit);
                        list_for_each_entry(file, files, list) {
                                if (!file->found && str_has_prefix(entry->d_name, file->name.buf))
                                        process_file(s.buf, file);

```

I usually don't write C so there will most likely be vastly better ways to go at this (e.g. including skipping the subsequent `list_for_reach_entry` if it really was a directory) but it does make the correct icons show up in the menu for me and seems to prove my point about the code behavior.

Hopefully this helps in finding a good solution.

**Comment by johanmalm** [comment]
@M4he thanks for help analyzing this.
Does this look okay? Works my machine. https://github.com/johanmalm/jgmenu/pull/177
