### ISSUE TITLE
'make test' failed on aarch64

### ISSUE THREAD

**Issue by tieugene** [johanmalm/jgmenu#123]
https://koji.fedoraproject.org/koji/taskinfo?taskID=46246932

**Comment by johanmalm** [comment]
It's test t1014-xpm.t which fails.

Are you able to enter the environment to run commands? If so, could you try

```
./configure
make
make test
cd tests
./helper/test-xpm t1014/gimp.xpm
```

Is t1014/gimp.xpm.png a valid .png file - i.e. can you view it?

I expect the output png file is causing the problem. Maybe a byte order problem or something like that.

Can you run jgmenu on that architecture to confirm that xpm icons are supported in the menu?
If that's the case I suggest that we just disable the test on that architecture.

**Comment by tieugene** [comment]
I use Fedora «cloud» build service (koji) for this, so it is not real «live» system - just automatic build.
So solutions are:
- install virtual ARM64 Fedora (or ant other distro) and try it.
- exclude this arch from tests now (bad but fast way) and leave issue for next release.

I have no enough resources to try 1st way (have P4 (exactly P4) 3.0 GHz CPU + 4GB RAM host w/o VTx).

**Comment by johanmalm** [comment]
I’ve disabled the test for the time being. If needed in future, I’ll do something that outputs text instead of png files.
