### ISSUE TITLE
Enhancement: Persistent mode

### ISSUE THREAD

**Issue by phedders** [johanmalm/jgmenu#129]
It would be great if there was a "--persistent" flag and the menu would stay open until Escape or ^Exit options were selected.

(PS jgmenu is wonderful - and looks great too. Thankyou)

**Comment by johanmalm** [comment]
Thanks for feedback.
PR accepted.
Have you got a use-case you'd be willing to share?

**Comment by napcok** [comment]
I'm also interested in use-case for that.
This could be a great feature if jgmenu in --persistent mode could not grab mouse and keyboard from whole screen and let interact with other applications - something like "sticky menu" (GNOME 1 and Window Maker had such a feature if I remember correctly)

**Comment by dumblob** [comment]
@napcok yes, what you describe would open a whole new set of use cases. But it depends on how much code it is to support it :wink:.
