### ISSUE TITLE
jgmenu lacks of responsivity on start-up

### ISSUE THREAD

**Issue by kilbith** [johanmalm/jgmenu#13]
When executing `jgmenu`, I can first see a black window, then the icons and text appear like 0.1s or 0.2s after. Something has to be done to speed this up.

On `LXPanel` for example, you directly see the icons/text without noticing any slowness at start-up.

**Comment by johanmalm** [comment]
Interesting. I don't get this - and I'm on a pretty slow computer.
Could you help me track down the issue?

How quick is it if you create a simple menu such as those described in JGMENUTUTORIAL(7) lessons 3-6. 

How fast is it if you disable icons by setting icon_size = 0 in your jgmenurc

What Composite Manager do you run? Could you disable it to see if that makes it faster.

What system are on (OS, Desktop Environment, Window Manager).
Are you a Virtual Machine?

What sort of times do get if you do:
cd tests
./t9000-icon-load.sh

As opposed to LXDE panel (and its menu) et al, jgmenu starts from scratch every time. We could consider keeping it running and toggling show/hide with a signal (e.g. SIGUSR1), but would have to re-think and re-write several aspects of jgmenu.

**Comment by kilbith** [comment]
Sorry, quick answer, I'm not using jgmenu anymore since I switched on Ubuntu recently.

> What Composite Manager do you run?
None.

> What system are on (OS, Desktop Environment, Window Manager).
OS: Arch Linux
WM: i3

> Are you a Virtual Machine?
No.

**Comment by johanmalm** [comment]
I understand the issue now. Thanks for raising it. It's the lack of a Composite Manager that does it. I always use one (normally compton), which is why I hadn't noticed it.
I get a fairly consistent start-up+die() time at around 160ms (with or without compton).
With compton, it looks nice and smooth. Without it, I get an ugly black background flash past (as you described).
I'll have a think about how we resolve it.

**Comment by kilbith** [comment]
Yeah, the animation from the compositor hides the startup {ugli,slow}ness. But now take e.g. `LXPanel`, it's fast and you don't see such things without compositor when opening the menu.

**Comment by johanmalm** [comment]
Sure.
jgmenu is similar to dmenu and dzen2 in that it starts from scratch every time it's called (feature or shortcoming depending on your view)
Most menus I can think of (incl `LXPanel`) are built-in to either the Window Manager or Panel and are therefore already loaded and running.
I guess we have a few options:
1. Reduce the start-up time. I could probably at least halve it.
2. Hide window until loaded (I've not looked at this yet - so will have to play with it).
3. Leave jgmenu running (as an optional feature) and toggle show/hide somehow.

I'll will try to achieve number 1 and 2.
Number 3 doesn't sit quite right with me yet - will have to give that some more thought.

**Comment by kilbith** [comment]
It's not a problem for me to run it as a daemon, I already do that for `urxvt`, it takes a really small memory footprint but the startup is damn fast.

**Comment by johanmalm** [comment]
Okay. Food for thought.

**Comment by johanmalm** [comment]
Kilbith
I've done number 3 :-)
Set "stay_alive = 1" in your ~/.config/jgmenu/jgmenurc
Then show menu with "killall -SIGUSR1 jgmenu"
