### ISSUE TITLE
Prompt, password or otherwise

### ISSUE THREAD

**Issue by KaffeMyers** [johanmalm/jgmenu#137]
Hi,

I'm trying to figure out if I can use jgmenu to prompt for user input, and right now looking for it to be used for as a password prompt (like * character replacement) to unlock bitwarden for my qutebrowser-bitwarden-jgmenu script. So, something akin to the current search bar, but which you can use to ouput whatever you write to some command.

I currently have it to make choices for more than one match, so it's starting to look pretty slick...

Is this possible? If not, is this a worthwhile feature to suggest?

**Comment by johanmalm** [comment]
Would the “--no-spawn” option work?
https://jgmenu.github.io/jgmenu.1.html

**Comment by KaffeMyers** [comment]
No, not as I understand it. I would like jgmenu to get something looking similar to the search bar, and whatever typed in to the bar piped out exactly as written -- simply a password prompt. This is to unlock the password manager in this particular case, so the password is not to be picked, but to be written out. I can see use for it in other cases as well, though.

The --no-spawn suggestion did however clean up another use of jgmenu in my script, so thanks for that! :+1:

**Comment by johanmalm** [comment]
I think this would require a lot refactoring and is not really in-line with the general direction of jgmenu
Would yad or zenity work for this?

**Comment by KaffeMyers** [comment]
Most likely, just would like to avoid additional dependencies and would be
a nice feature for various applications.

Too bad it's not an easy widget to add!

Thanks for all the great work you've done so far.
