### ISSUE TITLE
jgmenu fails to show Settings submenu

### ISSUE THREAD

**Issue by fdservices** [johanmalm/jgmenu#139]
The main menu shows up correctly and all the other submenus open as normal, but when I hover over "Settings" the main menu closes. 

The error shown running from the command line is:
$ jgmenu_run
warning: 'at_pointer' is deprecated; use 'position_mode'
warning: 'at_pointer' is deprecated; use 'position_mode'
info: created 8 symlinks in ~/.cache/jgmenu/icons/
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Value in failed request:  0x80
  Serial number of failed request:  3462
  Current serial number in output stream:  3560

jgmenu v4.2.1
Arch Linux 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux

**Comment by johanmalm** [comment]
Could you try without any config files in ~/.config/jgmenu to see how it behaves with default values.

Also, please could you paste the output of `jgmenu_run apps`

**Comment by fdservices** [comment]
Sorry, but it has started working correctly again.

It seems that it was a problem with the X server, relating to the graphics driver. Searches all seem to indicate an NVIDIA problem, but my graphic card is Intel. The only NVIDIA  package I have installed is libvdpau:
Required By     : ffmpeg  gst-plugins-bad-libs  libva-vdpau-driver  mplayer  mpv

The only Xorg error logged is:
(EE) event9  - MOSART Semi. 2.4G Keyboard Mouse: client bug: event processing lagging behind by 26ms, your 
system is too slow
I doubt if that was the problem.

I wonder why it only triggered when hovering over the Settings option an no other.

Since it is all working correctly now I think it is best to wait and hope that it does not happen again.

Thanks for the reply.

**Comment by johanmalm** [comment]
Okay. I’ll close it for now, but do just re-open if you can reproduce the problem.
