### ISSUE TITLE
Jgmenu stop displaying

### ISSUE THREAD

**Issue by RohitSingh107** [johanmalm/jgmenu#141]
Here is what I am doing and output I get.

$ jgmenu_run
warn: found old lockfile; lockfile removed
warning: XSupportsLocale(): error setting locale
warning: XSetLocaleModifiers(): error setting locale
info: created 10 symlinks in ~/.cache/jgmenu/icons/
info: created 21 symlinks in ~/.cache/jgmenu/icons/
Segmentation fault (core dumped)

**Comment by johanmalm** [comment]
Is your locale setup correctly?

```
echo $LANG
echo $LC_ALL
```

Does it work if you run with `LANG=C jgmenu_run`?

You can run `locale -a` to work out which locales are available to you. Set LANG to one of these.

**Comment by RohitSingh107** [comment]
> Is your locale setup correctly?
> 
> ```
> echo $LANG
> echo $LC_ALL
> ```
> 
> Does it work if you run with `LANG=C jgmenu_run`?
> 
> You can run `locale -a` to work out which locales are available to you. Set LANG to one of these.

It was my locale's problem. I changed my locale and it worked. Thanks .
