### ISSUE TITLE
src/jgmenu-obtheme.c: parsing for menu.title.bg.border.color which does not exist

### ISSUE THREAD

**Issue by johnraff** [johanmalm/jgmenu#142]
On this line:
https://github.com/johanmalm/jgmenu/blob/cfb409e884781caa27f2016c8b4e1e71102fbceb/src/jgmenu-obtheme.c#L103
jgmenu-obtheme.c is parsing for an OpenBox theme value _menu.title.bg.border.color_ which as far as I can tell from the [docs](http://openbox.org/wiki/Help:Themes) does not exist.

If this is indeed the case, then some other way to handle jgmenu's _color_title_border_ will be needed when syncing with an OpenBox theme. Maybe set to the same value as _color_menu_border_?

**Comment by johanmalm** [comment]
That's a great spot.
I think it'll be safest to just set it to the same as menu.title.bg.color
Do you agree?

**Comment by johnraff** [comment]
Yes, _menu.title.bg.color_ does look like the safest option.
