### ISSUE TITLE
Jgmenu - where did the name come from?

### ISSUE THREAD

**Issue by napcok** [johanmalm/jgmenu#152]
Hi,
I wonder where the name jgmenu came from and what it means.

I am asking because I have already written some small tools and pipemenus based on jgmenu. There are already a lot of them and their number is constantly growing. They are all written for the Mabox Linux project, but I plan to rewrite them in the future so that they are not distribution-dependent and publish somewhere. I wonder about a name for them, maybe "jgtools". What do you think?

**Comment by johanmalm** [comment]
Hi.
Just my initials. Nothing deeper I’m afraid.
Choosing something fairly unique was also a consideration.
Keen to have a look at your jgmenu tools. Are they on github?
Maybe “jgmenu-tools” could work.
Would the name just be for the repo/package, or also the prefix for each of the script/binary filenames?

**Comment by napcok** [comment]
Hi,
You can see lot of them on screenshots there: https://blog.maboxlinux.org/whats-new-in-mabox-20-10-eithne/
There ale maimenu, two sidepanels, screenshot tool, exit dialog and many more pipemenus (which can run standalone, as pipemenu or from tint2 panel). All written in Bash. I'm not happy how I wrote them...  which is another reason I consider rewrite all from scratch.
The code is in two places, here :
https://git.maboxlinux.org/Mabox/mb-jgtools/src/branch/master
and most of pipemenus here (those with prefix jg*):
https://git.maboxlinux.org/Mabox/mabox-pipemenus
