### ISSUE TITLE
handling more than one instance of jgmenu

### ISSUE THREAD

**Issue by elig0n** [johanmalm/jgmenu#153]
I have my window manager set to run `jgmenu --config-file=... --csv-file=... --simple` on startup and then use `jgmenu_run` whenever it is to be invoked. 

I also have another menu set-up to run with `--simple` (to bypass the other instance's lock) but after first activation of it, whenever `jgmenu_run` is called, both of the menus pop up.

According to the manual `--simple` should cause jgmenu to quit after selecting something or closing the menu. I don't see that it happenning to any of the spawned instances 

So how can I still manage several instances together ?

**Comment by johanmalm** [comment]
Looks like you discovered a bug. Now fixed.
