### ISSUE TITLE
config not working

### ISSUE THREAD

**Issue by DanHolli123** [johanmalm/jgmenu#154]
no matter how I change the config, refresh, or restart jgmenu, it just wont use my config file even if I tell it to by command

preappended items work fine, but I cannot for the life of me make space for it to be above my Tint2 dock

I know it can be repositioned because making it spawn near the pointer by command will in fact place it above the cursor

**Comment by johanmalm** [comment]
Okay, let's break it down in steps.

Are you sure that jgmenu is not reading/using the config file?

Could you paste the output of `cat $HOME/.config/jgmenurc`

If you start with a blank jgmenurc and just add somethink like `color_menu_bg = #FF0000 100`, would that work?

If the above works, then could you describe what config option you're wanting to change, what behavior you're expecting and what actually happens.

What's your system setup? (e.g. what's your distribution, are you running through VNC/VirtualBox/similar, are you running on X11 or Wayland?)

**Comment by DanHolli123** [comment]
Stock `~/.config/jgmenurc` asides from similar change `color_menu_bg = #FFFFFF 100` currently
does not change

Arch
direct hardware of old Toshiba Portege
X11 and started in Awesome (doesn't have compositing), but persists in Mate and LXDE
file owned by my user (non root)


-- Things I've tried --
I'm not near this computer at the moment so I can't directly copy the `/.config/jgmenurc`
initially was wanting to statically reposition it, didn't work (assumed it was just Awesome but checked config to be sure)
near pointer only worked with command line argument but too close for my use case
copy default config to ensure no errors and changed color_menu_bg color to white `#FFFFFF`

**Comment by johanmalm** [comment]
Let’s check the location of the file:

it should be $HOME/.config/jgmenu/jgmenurc

Probably my fault for mistyping in last post, but please confirm

**Comment by johanmalm** [comment]
Please shout if still not working.
