### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by napcok** [johanmalm/jgmenu#155]
I can see that quite important features have been added after the last 4.3.0 release. Like Path (Working Directory support).
Are there any chances for another release soon?

**Comment by johanmalm** [comment]
Ok. Will do.
Too tired tonight, but will do soon

**Comment by johanmalm** [comment]
https://github.com/johanmalm/jgmenu/releases/tag/v4.4.0

It's out. Thanks for the reminder to up-issue :smile:
