### ISSUE TITLE
Bottom menu margin

### ISSUE THREAD

**Issue by godalming123** [johanmalm/jgmenu#159]
Hi I am using jgmenu and like it. I just have one problem which is how do I add margin to the bottom of the menu. Because I use my panel at the bottom I would like jgmenu to be at the bottom left of the screen with bottom and left padding so it does not over lapp with the panel. But adding a negative value to the valign does not appear to work. Any help?

**Comment by Woynert** [comment]
Try with
```
position_mode = fixed
menu_margin_x = 10
menu_margin_y = 50
```

**Comment by godalming123** [comment]
Wouldn't that just give the menu top margin?

**Comment by godalming123** [comment]
Sorry, it does work
