### ISSUE TITLE
window name

### ISSUE THREAD

**Issue by misitiri** [johanmalm/jgmenu#163]
This isn't an issue, I just want to know the name of the window created when launching jgmenu. I want to write a script that affects all of the visible windows, but that currently includes the jgmenu window, which isn't desirable.

**Comment by johanmalm** [comment]
(sleep 2; xwininfo -name jgmenu)& jgmenu_run

Would this help

**Comment by johanmalm** [comment]
https://github.com/johanmalm/jgmenu/blob/2c73e235bb96a503572a06819cec96cf1d90a6e1/src/x11-ui.c#L265

I think this might be it

**Comment by misitiri** [comment]
that works, thank you
