### ISSUE TITLE
Several suggestions for enhancements 

### ISSUE THREAD

**Issue by PPC-scripts** [johanmalm/jgmenu#166]
Hi- I love jgmenu, and it's used, as menu in the ft10-transformation package, available in the antiX Linux repository (and over at https://gitlab.com/antix-contribs/ft10-transformation) , so I would like to suggest some enhancements: 
 - is it possible to parse the alphabetical order of menu entries only after getting the localized versions of the apps names (they are organized in alphabetical order of the original, usually English, name, not the in language the apps appear in the menu)?
 - Is it possible to add tooltips, that show up after the mouse pointer overs above an option for X time (Ex: 1 second)?
 - Is it possible to add a visible scroll bar? (If that feature is already available I don't know how to make that appear)

As it is, jgmenu is already a great piece of software, thanks for creating it!

**Comment by johanmalm** [comment]
Hi and thanks for your support.
My time is pretty limited on `jgmenu` development at the moment. Happy to do simple fixes and will of course review/merge sensible patches.

Regarding your first point, I've have a go at writing a fix. See below. Would you be able to try it with your language to confirm that it works.

Regarding tooltips, that requires tweaking the main event-loop and therefore needs lots of testing. Sort of not a high priority at the moment.

Regarding a scroll-bar, yes I agree that would be neat. I think it ought to be a widget. If you're a coder, happy to discuss approach - otherwise it'll have to be when I get time.


```
diff --git a/Makefile b/Makefile
index 3811819..8808d0f 100644
--- a/Makefile
+++ b/Makefile
@@ -16,12 +16,14 @@ jgmenu:         CFLAGS += `pkg-config cairo pango pangocairo librsvg-2.0 --cflag
 jgmenu-ob:      CFLAGS += `xml2-config --cflags`
 jgmenu-obtheme: CFLAGS += `xml2-config --cflags`
 jgmenu-config:  CFLAGS += `pkg-config --cflags glib-2.0`
+jgmenu-apps:    CFLAGS += `pkg-config --cflags glib-2.0`
 
 jgmenu:         LIBS   += `pkg-config x11 xrandr cairo pango pangocairo librsvg-2.0 --libs`
 jgmenu:         LIBS   += -pthread -lpng
 jgmenu-ob:      LIBS   += `xml2-config --libs`
 jgmenu-obtheme: LIBS   += `xml2-config --libs`
 jgmenu-config:  LIBS   += `pkg-config --libs glib-2.0`
+jgmenu-apps:    LIBS   += `pkg-config --libs glib-2.0`
 
 LDFLAGS += $(LIBS)
 
diff --git a/src/desktop.c b/src/desktop.c
index 8886eca..a94392b 100644
--- a/src/desktop.c
+++ b/src/desktop.c
@@ -9,6 +9,7 @@
 #include <string.h>
 #include <dirent.h>
 #include <stdbool.h>
+#include <glib.h>
 
 #include "desktop.h"
 #include "xdgdirs.h"
@@ -228,9 +229,13 @@ static int compare_app_name(const void *a, const void *b)
 {
 	const struct app *aa = (struct app *)a;
 	const struct app *bb = (struct app *)b;
+	const char *aa_name, *bb_name;
 
 	BUG_ON(!aa->name || !bb->name);
-	return strcasecmp(aa->name, bb->name);
+	aa_name = aa->name_localized[0] != '\0' ? aa->name_localized : aa->name;
+	bb_name = bb->name_localized[0] != '\0' ? bb->name_localized : bb->name;
+	return strcmp(g_utf8_casefold(aa_name, -1),
+		      g_utf8_casefold(bb_name, -1));
 }
 
 struct app *desktop_read_files(void)
```
