### ISSUE TITLE
How to set @rect and @icon positions

### ISSUE THREAD

**Issue by clemencyworld1** [johanmalm/jgmenu#167]
I am trying to edit greeneye jgmenu theme to resemble unity hud. Everything is working well until i started moving the @rect and @icon variables to the bottom of the menu. 

The @rect does not show up or show up when the mouse pointer is below the set position. 

The @icon variable shows at the right position but does not respond to mouse click even when the command portion is set.

I have done similar thing before where i added icons in behind the categories label  and it worked. I dont know what am doing wrong.

I know you are kinda busy but i will appreciate if my issue is looked into. Jgmenu is a great software; the only launcher i use in my setup aside yad.

**Comment by clemencyworld1** [comment]
I will send my config file and draft csv fike for evaluation

**Comment by clemencyworld1** [comment]
csv_cmd             = apps
tint2_look          = 0
menu_width          = 800
menu_height_min     = 450
menu_height_max     = 450
menu_padding_top    = 40
menu_padding_right  = 250
menu_padding_bottom = 100
menu_padding_left   = 20
menu_border         = 2
item_height         = 70
item_radius         = 2
item_border         = 1
color_menu_bg = #592E39 50
color_menu_border   = #eeeeee 20
color_norm_fg = #ffffff 100
color_sel_bg = #e47c37 100
color_sel_fg = #ffffff 100
color_sel_border    = #eeeeee 8
color_scroll_ind    = #000000 0
csv_name_format     = %n\n<span size="x-small">%g</span>
csv_no_dirs         = 1
color_title_fg = #5a5a5a 100
color_title_bg = #303842 100
color_title_border = #303842 100
# verbosity = 0
stay_alive = 0
# persistent = 0
# hide_on_startup = 0
position_mode = fixed
# edge_snap_x = 30
terminal_exec = sakura
terminal_args = -e
# monitor = 0
# hover_delay = 100
# hide_back_items = 1
columns = 4
# tabs = 120
menu_margin_x = 57
menu_margin_y = 20
# menu_height_mode = static
menu_radius = 5
menu_halign = left
menu_valign = top
# menu_gradient_pos = none
# sub_spacing = 1
# sub_padding_top = auto
# sub_padding_right = auto
# sub_padding_bottom = auto
# sub_padding_left = auto
# sub_hover_action = 1
# item_margin_x = 3
# item_margin_y = 3
# item_padding_x = 4
# item_halign = left
# sep_height = 5
# sep_halign = left
# sep_markup = 
font = Arial 7
# font_fallback = xtg
 icon_size = 48
 icon_text_spacing = 10
 icon_norm_alpha = 80
 icon_sel_alpha = 100
 icon_theme = pantheon
 icon_theme_fallback = adwaita
# arrow_string = ▸
# arrow_width = 15
# color_menu_bg_to = #000000 100
# color_norm_bg = #000000 00
# color_sep_fg = #ffffff 20
csv_single_window = 1
# csv_i18n = 
# csv_no_duplicates = 0

**Comment by clemencyworld1** [comment]
This is my jgmenurc

**Comment by clemencyworld1** [comment]
@rect,,0,0,782,432,2,left,top,#000000 0,#4B1418 100,

@rect,,10,8,515,30,4,left,top,#ffffff 100,#23060A 100,
@search,,35,6,240,36,2,left,top,#eeeeee 80,#000000 0,Search Applications
@icon,,16,12,22,22,2,left,top,#000000 50,#000000 50,/home/standard/.config/jgmenu/greeneye-search.svg

@rect,,0,403,783,30,0,left,top,#ffffff 0,#3A0E0F 100,

@rect,^filter(*),60,400,50,30,2,left,top,#000000 0,#000000 0,
@text,^filter(*),84,406,50,30,2,left,top,#e6e6e6 100,#000000 0,All

@rect,^filter(#Accessories #Util #Archiving #Compression #TextEditor ),144,406,50,30,2,left,top,#000000 0,#000000 0,
@text,^filter(#Accessories #Util #Archiving #Compression #TextEditor ),144,403,50,30,2,left,top,#e6e6e6 100,#000000 0,Acc

@rect,^filter(#Development #Build #Debug #IDE #Profiling #RevisionControl ),174,403,50,30,2,left,top,#000000 0,#000000 0,
@text,,179,403,50,30,2,left,top,#e6e6e6 100,#000000 0,Dev

@rect,^filter(#Game ),214,403,50,30,2,left,top,#000000 0,#000000 0,
@text,,219,403,50,30,2,left,top,#e6e6e6 100,#000000 0,Gam

@rect,^filter(#Graphics #Scanning #Photography ),274,403,50,30,2,left,top,#000000 0,#000000 0,
@text,,279,403,50,30,2,left,top,#e6e6e6 100,#000000 0,Gra

@rect,^filter(#Internet #Network #Email #FileTransfer #WebBrowser ),334,403,50,30,2,left,top,#000000 0,#000000 0,
@text,,339,403,50,30,2,left,top,#e6e6e6 100,#000000 0,net

@rect,^filter(#Multimedia #Player #Audio #Video #Recorder ),384,403,50,30,2,left,top,#000000 0,#000000 0,
@text,,389,403,50,30,2,left,top,#e6e6e6 100,#000000 0,med

@rect,^filter(#Office #Calendar #Contact #Dictionary #Chart #Finance #Presentation #Spreadsheet #WordProcessor #Publishing #Viewer ),434,403,50,30,2,left,top,#000000 0,#000000 0,
@text,,439,403,50,30,2,left,top,#e6e6e6 100,#000000 0,Off

@rect,^filter(#Settings #Security #Preferences ),484,403,50,30,2,left,top,#000000 0,#000000 0,
@text,,489,403,50,30,2,left,top,#e6e6e6 100,#000000 0,Set

@rect,^filter(#System #Emulator #FileManager #TerminalEmulator #Filesystem #Monitor ),534,403,50,30,2,left,top,#000000 0,#000000 0,
@text,,539,403,50,30,2,left,top,#e6e6e6 100,#000000 0,Sys

**Comment by clemencyworld1** [comment]
And this is my draft append.csv

**Comment by clemencyworld1** [comment]
screenshot

**Comment by clemencyworld1** [comment]
Cant seem to attach screenshot

**Comment by johanmalm** [comment]
Thank you for reporting this. You've discovered a bug and I will push a fix shortly.
Nice setup!

![20220312_15h54m29s_grim](https://user-images.githubusercontent.com/6955353/158025257-afb6e2a6-3dde-40fa-878c-bccf428f0c50.png)

**Comment by clemencyworld1** [comment]
Thanks. Looking forward to that.

**Comment by johanmalm** [comment]
Sorry. Took longer than anticipated. Hopefully it works now. Would appreciate feedback.
