### ISSUE TITLE
^tag showed without checkout

### ISSUE THREAD

**Issue by purpleleaf** [johanmalm/jgmenu#171]
Jgmenu version 4.4.0 compiled from git clone, with gtktheme support
Using the followig prepend.csv:

```
@icon,,0,0,40,40,5,,,,,/usr/share/icons/Papirus-Dark/symbolic/apps/system-users-symbolic.svg

^tag(test)
palemoon,palemoon,palemoon
Back,^checkout(apps)

```
the Palemoon icon is showed before the app menu, no "Back" text showed.

**Comment by johanmalm** [comment]
This is working as I expect it to.

The root-menu has a tag too. It is not necessary to define it with a ^tag(), but if you choose to do that as the first item, that’s fine :)

The ^checkout(apps) is ignored because you haven’t defined a ^tag(apps) anywhere
