### ISSUE TITLE
imlib2 cannot render jgmenu icon

### ISSUE THREAD

**Issue by ATM-Jahid** [johanmalm/jgmenu#172]
`imlib2` cannot render the jgmenu svg icon since its `1.8` release. The programs which use `imlib2` to render icons thus leave the jgmenu program iconless.

Here's what I observed:
- After downgrading `imlib2` to version `1.7.5`, the programs `tint2` and `feh` were able to render the jgmenu icon.
- Other svg icons do not face this problem. For example, Alacritty's svg icon is rendered just fine. I have not checked all svg icons there are, but it works for all other icons I checked.

**Comment by johanmalm** [comment]
Thanks for reporting. Hopefully that works.
