### ISSUE TITLE
Applications grouped in submenus by category

### ISSUE THREAD

**Issue by o9000** [johanmalm/jgmenu#2]
On most Linux systems, in addition to the ` .desktop` files that describe application shortcuts, there are also `.directory` files that describe the start menu structure. On Debian they are part of the `gnome-menus` package.

Do you think it makes sense to load the categories from there in jgmenu_xdg?

Some time ago I wrote a Python script that does this: https://gitlab.com/o9000/pmenu/blob/master/pmenu.py

There are screenshots of the result in https://gitlab.com/o9000/pmenu

**Comment by johanmalm** [comment]
Yes. I'll have a go at this after "icons".

**Comment by johanmalm** [comment]
I've committed jgmenu-pmenu which is based on "https://gitlab.com/o9000/pmenu/blob/master/pmenu-jgmenu.py". With that I think that this issue can be parked.
