### ISSUE TITLE
EDIT: Mouse cursor sometimes disappears when outside menu

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#23]
Sometimes mouse cursor disappears if submenu is shorter than current menu and after click cursor is left over another window. It may be limited to situations where that window is a terminal that jgmenu was launched from.
If that happens, cursor is only visible when over menu. It restores when menu is closed.

**Comment by johanmalm** [comment]
I've never noticed that before, but I can reproduce it on both BunsenLabs and Ubuntu.
I've had a quick play with the XGrabPointer() settings, but it doesn't seem to make a difference.
I'll have to dig a bit deeper. Thanks for raising it.

**Comment by johanmalm** [comment]
I can't find a solution to this. Maybe it's an X11 bug?
I'll set to 'wontfix' and close unless you think there is anything else I should try.
