### ISSUE TITLE
Question about tint2 config search

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#25]
Does jgmenu take into account the fact that tint2 may use custom config file path, or multiple instances of it may be running?
If not, here is a proposed algorithm:
* if there exists tint2 process without `-c` argument, or there are no tint2 processes in current session, use tint2rc found in XDG dirs normally.
* if there are only tint2 processes in current session with `-c` arguments, prioritize those pointing inside $HOME, then, IDK, choose alphabetically.

**Comment by johanmalm** [comment]
I think reading $TINT2_CONFIG from the environment is quite a good solution.

Run the following to try it :-)
`cd examples; ./ex10.sh`

I looked at finding tint2 processes and parsing associated -c arguments, but concluded that there are many 'edge cases' and that it would be tricky to keep both fast and POSIX compliant. And if multiple instances are running, there is no way of picking the right one anyway.

TINT2_CONFIG is populated by tint2 when using buttons, launchers, etc, enabling us to pick the right one if multiple tint2 processes are running
