### ISSUE TITLE
Search does not work with non-english layout

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#26]
stdout consists of empty lines while typing, search isn't activated.

**Comment by Vladimir-csp** [comment]
Great! Search works, but there are issues:
hitting backspace removes bytes, not characters.
"Back" items can be matched with search and are listed multiple times.

**Comment by johanmalm** [comment]
How is that for a response :-)

Although I've only done limited testing, I think that's it for this issue.

Not sure how to do case-insensitive strcasestr for unicode. I think I'll leave that for another day.

**Comment by johanmalm** [comment]
I've removed the ^back() items too. Good spot. Thanks
