### ISSUE TITLE
XDG-based configuration

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#27]
Please implement standard XDG-based configuration with global configuration in `${XDG_CONFIG_DIRS:-/etc/xdg}` directory list and user configuration override in `${XDG_CONFIG_HOME:-$HOME/.config}`

**Comment by johanmalm** [comment]
Thanks for raising all these. You've got some really good ones there.
It might take me a while to get through them, but I do really appreciate your input.

**Comment by johanmalm** [comment]
Done.
