### ISSUE TITLE
Terminal=true entries

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#28]
To support these there should be some way to set a terminal emulator and it's exec arguments, something like this:
```
# pass command as arguments
terminal=xterm -e %a
# pass command as a string
terminal=qterminal -e %s
```

**Comment by johanmalm** [comment]
Could I just run this by you?

What I had in mind was adding the markup `^term()` where `^term(foo)` would expand into `your_favourite_terminal -e 'foo'`
This would let jgmenu.c handle the launch of the terminal, and thus make pmenu and lx a bit simpler (i.e. all they need to do is add ^term(...)) 

I could write a quick term.c which would pick a terminal from a pre-defined array (e.g. x-terminal-emulator, terminator, gnome-terminal, qterminal, uxterm, urxvt, etc...) depending on what we can find in $PATH. 
I think it would make sense to also give the user the option to overrule any such automatic selection of terminal by setting a config option (like you suggested). E.g. `terminal=xterm`

Just to clarify, in your example, are %a (arguments) and %s (string) the same thing or am I missing a point?

**Comment by Vladimir-csp** [comment]
OK, `-e` should be a part of configurable terminal command, as not every terminal emulator uses `-e` as an execution argument.

String versus array of arguments... on second thought if it is possible to pass arguments as is, that would probably be the way.
Try running:
```
xterm -e nano "some file with spaces"\ and\ unquoted\ spaces second\ file
```
Xterm does this right. With other terminals results may wary.

**Comment by Vladimir-csp** [comment]
By the way, I'm trying to push a proposal for default terminal standard to XDG. It's in the thread [here](https://lists.freedesktop.org/archives/xdg/2017-May/013911.html), and my implementation is [here](https://github.com/Vladimir-csp/xdg-terminal-exec). Work in progress.

**Comment by johanmalm** [comment]
I like the xdg-terminal-exec idea. Looks very tidy. It would certainly solve this issue. I'm surprised it doesn't already exist - but I suppose it's like that with good ideas... it's obvious when you see it.

Just one thought, would it work across other terminals if you hard quoted the command?

`favourite_terminal -e 'nano stuff\ with\ spaces "second file"`

I tried gnome-terminal. It didn't work without, but worked with.

**Comment by Vladimir-csp** [comment]
Your command has unclosed hard quotes.
Anyway, backslashes inside quotes are usually treated literally.

**Comment by Vladimir-csp** [comment]
I filed bugs for [sakura](https://bugs.launchpad.net/sakura/+bug/1693988) and [qterminal](https://github.com/lxde/qterminal/issues/335)

**Comment by johanmalm** [comment]
Okay. I think it's done with the exception of adding a couple of config options if the user wants to overrule the defaults.

**Comment by johanmalm** [comment]
Now complete I think. :-)
