### ISSUE TITLE
Fields are passed literally

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#32]
For example, spacefm.desktop:
```
...
Exec=spacefm %F
...
```
is executed literally as `spacefm %F`. Fields should be dropped.

~Also there is a special case in ocrfeeder.desktop: `Exec=ocrfeeder -i %f` which can not be launched as `ocrfeeder -i`, but I didn't find any indication of argument removal in the spec, so this case would have to wait.~ never mind, only the field should be dropped. Ocrfeeder has invalid desktop entry.

**Comment by johanmalm** [comment]
Vladimir, great feedback.
I've implemented :)

**Comment by Vladimir-csp** [comment]
it works, thanks!
