### ISSUE TITLE
jgmenu vs openbox pipe-menu

### ISSUE THREAD

**Issue by paoloschi** [johanmalm/jgmenu#35]
I use Openbox WM exclusively and I do a bunch of bash scripts for any automation i need..
I just found jgmenu and I really like the fact that to define the voices there is only to follow a CSV schema: producing XML language from Bash for Openbox menus is quite tedious..

However, I am a bit less comfortable with the content definition structure required by jgmenu: if I understand correctly, I must first put all of the entries of level 0 (root) and then subsequently queue, with the ^(tag) directive, the contents for level 1 of the sub-menus (and so on) in the same STDIN or file definition..
This is by no means limitative if jgmenu is meant to be used as a desktop menu just for launch applications by  .desktop files but, if I want to build a menu for an application where menu items can often change, then the script often will have to redefine the entire menu, including for changing even a single item in a sub-menu (..)
From this point of view, the 'dynamic menu' or pipe-menu technique offered by Openbox to me it seems more advantageous from the perspective of Bash scripting versatility..

Did I not understand the project goal? Could there be future changes to facilitate a sort of bash dynamic scriptability of jgmenu?
(since english is not my language: I hope you can understand what I wanted to express ..)

**Comment by johanmalm** [comment]
Hi. Thanks for your feedback. It's great to have you onboard.

Yes. You are correct about the construct of the CSV file (root first, then ^tag() sections).

I intend to add support for pipe menus (see TODO file - plan for v0.9). Maybe ^pipe() or similar.

At the moment you could do something like this to simulate a pipemenu:

`xterm,xterm
pipe,cat another_file.csv | jgmenu --vsimple`

You can run `jgmenu_run ob` for an openbox menu, but as you've pointed out, we need proper pipemenu support to become more useful.

**Comment by paoloschi** [comment]
Fabulous, i will stay assiduously tuned for sure!!!! :-D

btw, I'm a Void Linux user and a few days ago I've request the packaging of jgmenu for the official repository of my distro.
There is a maintainer candidate who has been involved in the thing but oddly his build fails and now the situation seems to be stalled :-[
It sounds weird because I have not encountered any difficulties in compiling jgmenu and he is certainly more experienced than me..

You can read the entire story [here on github](https://github.com/voidlinux/void-packages/issues/7004)
and he posted [here](https://bpaste.net/show/34f5da6ae647) the log with the error
I was wondering if maybe you could go into the discussion to help him?

**Comment by johanmalm** [comment]
I think it's solved.
My Makefile.inc didn't allow for pre-set CFLAGS and LDFLAGS. I've upversioned to v0.6.1 to avoid the patch.

**Comment by paoloschi** [comment]
Thanks johanmalm for your interest to the Linux Void cause and I am happy if so we can now get jgmenu as official package!

**Comment by johanmalm** [comment]
That's great! I will try it out.

I've made a first commit towards pipemenus. It seems to work fine.
I haven't put anything in the documentation yet, but it's quite simple. Just do a ^pipe(my_menu_command) in the cmd-field (second field).

The pipe needs to start with a ^tag() item.

I'll tidy up jgmenu-parse-ob.c next to work with ^pipe()

**Comment by paoloschi** [comment]
I've finally found the moment to compile and try this beautiful novelty.
I'm playing with this banal test...
```
echo "pixmaps,^checkout(pixmaps)
pixmaps,^tag(pixmaps)
display,^pipe(echo -e '^tag()\n$(find /usr/share/pixmaps -type f -printf '%f,display %p,%p\n')')
" | jgmenu --simple
```
..and I wonder where I'm wrong: I thought in this way to get the pipe-menu as sub-menu of the 'display' entry.
instead, 'display' -as a empty sub-menu item- and all pipe entries are at the same level of the 'pixmaps' sub-menu
Sorry but, as you can see, I have not yet understood how it should be written instead..

**Comment by johanmalm** [comment]
On phone. Will try it tonight.
In your pipe, you might need to use weak quotes and put a name in tag.
Some shells don't do echo -e well. 
Try this the pipe (not tested)
`echo "^tag(foo)"; find /usr...`

**Comment by paoloschi** [comment]
ok, changed command this way
```
echo ^tag\(foo\); find /usr/share/pixmaps -type f -printf '%f,display %p,%p\n'
```
the output of this in my bash shell it is:

```
^tag(foo)
logo.png,display /usr/share/pixmaps/uget/logo.png,/usr/share/pixmaps/uget/logo.png
avidemux.png,display /usr/share/pixmaps/avidemux.png,/usr/share/pixmaps/avidemux.png
bleachbit.png,display /usr/share/pixmaps/bleachbit.png,/usr/share/pixmaps/bleachbit.png
filled-xterm_32x32.xpm,display /usr/share/pixmaps/filled-xterm_32x32.xpm,/usr/share/pixmaps/filled-xterm_32x32.xpm
filled-xterm_48x48.xpm,display /usr/share/pixmaps/filled-xterm_48x48.xpm,/usr/share/pixmaps/filled-xterm_48x48.xpm
geeqie.png,display /usr/share/pixmaps/geeqie.png,/usr/share/pixmaps/geeqie.png
htop.png,display /usr/share/pixmaps/htop.png,/usr/share/pixmaps/htop.png
mini.xterm_32x32.xpm,display /usr/share/pixmaps/mini.xterm_32x32.xpm,/usr/share/pixmaps/mini.xterm_32x32.xpm
mini.xterm_48x48.xpm,display /usr/share/pixmaps/mini.xterm_48x48.xpm,/usr/share/pixmaps/mini.xterm_48x48.xpm
obconf.png,display /usr/share/pixmaps/obconf.png,/usr/share/pixmaps/obconf.png
openbox.png,display /usr/share/pixmaps/openbox.png,/usr/share/pixmaps/openbox.png
terminator.png,display /usr/share/pixmaps/terminator.png,/usr/share/pixmaps/terminator.png
[....]
```

jgmenu shows `root/pixmaps/display/<empty>`

I think it will be better if I find another example to get started.. :)

**Comment by paoloschi** [comment]
now I've put the command in a separate script `pipecmd.sh`

```
#!/bin/bash
echo ^tag\(foo\); find /usr/share/pixmaps -type f -printf '%f,display %p,%p\n'
```
and this way..
```
#!/bin/bash
echo "pixmaps,^checkout(pixmaps)
pixmaps,^tag(pixmaps)
display,^pipe(/home/user/TEMPORARY/pipecmd.sh)
" | jgmenu --simple

```
..it works!!
although there is no rendering of images, which I had at the first attempt yesterday..

**Comment by johanmalm** [comment]
Good work. Looks like you've solved it.

Three thoughts from me:

1. The following line won't work because jgmenu will treat the commas in the -print

`display,^pipe(echo -e '^tag()\n$(find /usr/share/pixmaps -type f -printf '%f,displ

For the time being, if you're happy to create a script as you've done, that solves

I'm open to suggestions as to how it could be solved. The simplest solution might b
`Name,"command with,lots,of,commas",/usr/share/icons/some_icon`

Although it might be better to replace the " with some other symbol that's not used
Unless we accept that that there will never be more than three fields and that the 

2. Icons are not loaded for ^pipe() items yet. It's in my local TODO2, I've just no

So this would display icons:
`find /usr/share/pixmaps -type f -printf '%f,display %p,%p\n' | jgmenu --simple`

But something like this would not:

`(
echo "Firefox,firefox"
echo "Applications,^pipe(jgmenu_run parse-pmenu)"
) | jgmenu --simple`

3. I will remove the requirement to start a pipe with a ^tag(something) item.

**Comment by johanmalm** [comment]
P.S. I've installed Void on my laptop next to Bunsenlabs. I like it very much.

**Comment by paoloschi** [comment]
> but I'm not keen to build in barriers for future development.

completely agree!!!! ..in a real and non-trivial situation (like was this my first test), leaning on a separate script, I think, is the most correct and convenient way to go..

The P.S. about Void makes me very happy :-)
Myself I never used the Void installer! I start from the 'base-voidstrap' package and a few others (just ~30Mb at the first download) so then I can build the system  'brick on brick' at my pleasure;
from the live cd:
```
pkgs="base-voidstrap acpid lsof rsync sv-helper usbutils wget .."
xbps-install -MiS -R "$mirror" -r "$target" $pkgs
```
followed by a chroot to complete the installation with at least a kernel and a bootloader..
it is a pleasure to me (along with other peculiarities: no systemd, xbps-src, musl libs, libressl, etc ..) but here it is not the place to discuss it and I am totally O.T., sorry

**Comment by o9000** [comment]
> The following line won't work because jgmenu will treat the commas in the -printf argument as 'field separators' when CSV-parsing the whole line. I.e. the command field will stop after %f

A possible solution: https://tools.ietf.org/html/rfc4180

**Comment by johanmalm** [comment]
Thanks o9000. Useful link. I'm leaning towards covering three syntaxes
1. aaa,bbb,ccc (current syntax - can't contain commas)
2. aaa,"""bbb""",ccc (bbb can contain commas, and shell scripting can be done without replacing weak quotes with double-weak quotes, therefore improving readability)
3. "aaa","bbb","ccc" (compliance with 'adopted' standard)

**Comment by johanmalm** [comment]
I think this is done now.

I've removed the requirement to start with a `^tag()` item, so you can simply do something like:
`^pipe(ls -1)`

If you want to include commas within the pipe, use triple quotes. For example
`pixmaps,"""^pipe(find /usr/share/pixmaps -type f -printf '%f,display %p\n')"""`

I'll update the documentation to reflect this.

**Comment by johanmalm** [comment]
Shout if I've missed something.
