### ISSUE TITLE
^sep() text string font

### ISSUE THREAD

**Issue by paoloschi** [johanmalm/jgmenu#36]
In Openbox preferences, you can define a different character for the separation headers strings
Is this also possible in jgmenu? I do not find it in the documentation..

**Comment by johanmalm** [comment]
It's a good point. I'll implement that.
We should probably have a few other options for the separators too (colour, style, etc).

**Comment by paoloschi** [comment]
thank you!

**Comment by johanmalm** [comment]
Have added config options sep_markup and sep_halign. 

See this link for markup options:
https://developer.gnome.org/pango/stable/PangoMarkupFormat.html

Will update man pages and then close this issue.
