### ISSUE TITLE
[Solved] sublime text /opt

### ISSUE THREAD

**Issue by mrneilypops** [johanmalm/jgmenu#38]
I have sublime text installed but it does not show in the menu.
As per usual practice re: sublime the app is installed to /opt and symlinked to /usr/bin

`sudo ln -s /opt/sublime_text_3/sublime_text /usr/bin/sublime`

Any ideas how to get this app to show in jgmenu would be appreciated.

**Comment by johanmalm** [comment]
Hi. If you're using pmenu (which is default if you just run `jgmenu_run`), it will search for .desktop files in /usr/share/applications/
Do you have a sublime.desktop?
If not, you could create ~/.config/jgmenu/prepend.csv with the following line in it:
`Sublime,sublime,sublime`

**Comment by johanmalm** [comment]
If there is no sublime-text.desktop or similar, you could create one and put it in `~/.local/share/applications/`

**Comment by mrneilypops** [comment]
Thanks! Fixed and prepended a couple more apps as per;

`Firefox,firefox,firefox
Thunar,thunar,system-file-manager
Termite,termite,utilities-terminal
Sublime,sublime,sublime-text-editor
^sep()
![2017-08-13-215356_1920x1080_scrot](https://user-images.githubusercontent.com/1450448/29252984-8a3e0e70-8072-11e7-98b3-5879bed47fca.png)
`

**Comment by mrneilypops** [comment]
Update!
Now I found the icons!
prepend;
`Firefox,firefox,firefox
Thunar,thunar,system-file-manager
Termite,termite,utilities-terminal
Sublime,sublime,sublime
^sep()`

append;
`^sep()
#Exit to prompt,openbox --exit,system-log-out
#Suspend,systemctl -i suspend,system-log-out
Reboot,sudo reboot,gtk-refresh
Poweroff,sudo poweroff,system-shutdown`

![2017-08-13-224638_1920x1080_scrot](https://user-images.githubusercontent.com/1450448/29253317-4d697a0a-8079-11e7-9982-a5eaaa95d94c.png)

**Comment by johanmalm** [comment]
Scrots look great.
