### ISSUE TITLE
EDIT: save exit tag

### ISSUE THREAD

**Issue by paoloschi** [johanmalm/jgmenu#39]
I resumed a bash project where there will be a menu for the main application and where there are an indefinite number of possible additional plugins, each of which will have now its own standalone jgmenu menu.
( for this reason, I run every menu with the `--simple` option and a different `--csv-file=<file>`; each one of plugin's menus has an entry to invoke the main menu and everything goes flawlessy :)

well, it would be very helpful if each of the menus could reopen to the same level as it was closed, which I can easily get with the syntax

    jgmenu --simple --checkout <the pertinent check-out string> .....

My question is: what is the way, if it exists, that I can memorize the current check-out value (for example, in a temporary file?) and then resume it at the next jgmenu run by my scripts, at runtime?

If this is not currently feasible, could it be a new feature that would be useful to implement?

**Comment by johanmalm** [comment]
Good question :)

That's how jgmenu-parse-ob worked until recently (see commit bb81ce on 12 Aug). The parent passed a --return-cmd=whatever to child. The return-cmd would contain --checkout=some_tag. It felt a bit hacky and was mostly just an interim solution until I got around to doing ^pipe()

Would ^pipe() not work for this? I think that could be the neater solution.

In your example, instead of using --csv-file=the_file, you might be able to do
`jgmenu --simple --csv-cmd="cat the_file | sed -e 's/foo/the_parent_tag/'"`
assuming that "the_file" contains a --checkout=foo

I suppose another solution would be to export an environment variable when you call jgmenu --csv-file=something; like this:
`export JGMENU_RETURN_TAG=foo; jgmenu --simple --csv-file=bar`

If you can see a more elegant solution with jgmenu setting an environment variable (or writing to a temporary file), I'm quite happy to implement.

**Comment by paoloschi** [comment]
> If you can see a more elegant solution with jgmenu setting an environment variable (or writing to a temporary file), I'm quite happy to implement.

I would not know if it is the most elegant way but the conviction that would be the most 'good for any situation', I have that!
In your suggestions, I see references (the_parent_tag, _RETURN_TAG) as directives that seem 'relative' to a tag that must still be known to me (?)
In my view, regardless of everything (wholly static or ^pipe menu, whatever the level is open now..), it would be a benefit from the fact that jgmenu, at the time of exit, could optionally write the value of the current tag somewhere..
Your exquisite willingness gives me the courage to officially promote the thing from a 'simple idea' to 'official request' :-)
On the choice of environment variable or file, I wish it was, as much as can be expected, the most welcome one for all jgmenu users.

To say, my personal preference is to create, for each project, a support directory "${UID}-program_name" in /tmp and keep everything in there;
the fact that environmental variables are subjected to the 'scopes', rarely but has complicated my life in the past (..)

If instead you see it better to adopt a variable, perfect!, it will certainly be fine for me as well!

**Comment by johanmalm** [comment]
>  'relative' to a tag that must still be known to me (?)

Have you got an example I could look at? I can only think of situations where we could know the tag.
1. If you've hand-crafted the CSV file, you know the tag. The line that calls `jgmenu --csv-file...` comes under a `^tag(foo)` section.
2. If the CSV file is produced by code, we will also know the tag (such as in jgmenu-parse-ob.c before it started using ^pipe() last week).

I'm very happy to add "export..." or "setenv()" to support this, but if I understand the case where it's needed I can make sure we get it right. It would be a simple change in jgmenu.c to the some of the functions that call spawn()

Or if you want me to do "just do it" so you can play with it, I'm also happy to do that. In that case I would just do a
`setenv("JGMENU_RETURN_TAG", menu.current_node->tag, 1);`
before `spawn(...)`

**Comment by paoloschi** [comment]
My reasoning is elementary but I can make it complicated when I write here, 'cause of my lack of familiarity with the English language :-/
I made this example that will also allow me to add a second question, enough on the subject..

````
menu,^tag(root)

all items,^checkout(all items)
group 1,^checkout(group 1)
group 2,^checkout(group 2)

all items,^tag(all items)
item 1,^checkout(item 1)
item 2,^checkout(item 2)
item 3,^checkout(item 3)
item 4,^checkout(item 4)

group 1,^tag(group 1)
item 1,^checkout(item 1)
item 2,^checkout(item 2)

group 2,^tag(group 2)
item 3,^checkout(item 3)
item 4,^checkout(item 4)

item 1,^tag(item 1)
item 1 cmd 1,true
item 1 cmd 2,true
item 1 cmd 3,true

item 2,^tag(item 2)
item 2 cmd 1,true

item 3,^tag(item 3)
item 3 cmd 1,true
item 3 cmd 2,true
item 3 cmd 3,true
item 3 cmd 4,true

item 4,^tag(item 4)
item 4 cmd 1,true
item 4 cmd 2,true
````

A definition, therefore, totally static where I actually know each tag.
This is the menu that comes out of it:

````
  level 0                level 1              level 2
 ~~~~~~~~~              ~~~~~~~~~           ~~~~~~~~~~~~
|all items  > ---------|item 1  > ---------|item 1 cmd 1
|group 1    > ---      |item 2  > ..       |item 1 cmd 2
|group 2    > -  \     |item 3  > ..       |item 1 cmd 3
               \  \    |item 4  > ..
                \  \
                 \  ---|item 1  > ---------|item 1 cmd 1
                  \    |item 2  > ..       |item 1 cmd 2
                   \                       |item 1 cmd 3
                    ---|item 3  > ..
                       |item 4  > ..
````

Now i run

    jgmenu --simple --csv-file=menu.def --checkout="item 1"

and the menu opens directly to level 2, showing me the entries for "item 1": perfect, that's what I expected, beautiful feature..
This possibility caused my request to arise: when, later or tomorrow, I launch my application again, in case it would be profitable to reopen the menu directly at whatever level it was closed, how can I know the "tag" string value that I should pass to the "--checkout" option to obtain this?
Or if I need to run all "item 1" commands in sequence just now, how I would to avoid the navigation from root to level 2 three times below?..
Elementary, Watson! Just running the command above 3 times same equal!!
OK, BUT....

> [..] I can only think of situations where we would know the tag.

for "i do not know the tags" i mean, for example: my ^pipe()  script extracted data from a database and built the menu definition using as 'tag' string values found in the database, still unknown to me..
This is what I did in the application I am writing, a real situation.
Everything works very well but I have no way to take advantage of "--checkout" just because I do not know the value to pass it

My naïve reasoning: if jgmenu (that every time quits 'cause, as I wrote in the first comment, I always need to apply the "--simple" option), a moment before to exit it might somehow store the last visited tag with a mode I can subsequently easily access from Bash in separate session, I would then always know the right value to put at the "--checkout" option..
I have conceived this because it seems to me that this way the nature of the menu definition no longer matters: whether it is static or dynamically constructed with ^pipe() or that I know or do not know which tags are present, it should work in any (99.9%?) case! ..or is not it so?
I hope I did a better explaining this time.

----
The second annotation on my specific example:
you see that several times I have twice defined a same ^checkout() instance.
for example, this way I got "item 1" both in the "all items" and in "group 1" sub-menues
I wonder if there is no better way but this it looks good because so I just need to define "item 1 cmd 1" once for having it then whenever the "item 1" sub-menu appears: if "item 1" would contain hundreds of commands, it is really convenient..
If I distinguish between the two "^checkout()", how can I then avoid defining the same "cmd" entries several times?

In my example everything works fine with just one small exception:
I never leave the menu session.
If I did "all items/item 1" and now, al level 2, I press the right mouse button, I go back to the "item 1" sub-menu: perfect!
If I did "all items/group 1", coming back (the same if I had introduced a voice `item 1,^back(item 1)` at level 2) I would expect to find myself in the immediately preceding "group 1" sub-menu but now I'm transported to the "all items" sub-menu again (in the sequence, always returning to the first instance of "item 1" in the menu definition).

I'm still learning how to properly define the menus and probably my example is full of mistakes..
If it was acceptable, could the behavior I described be corrected?

If I'm becoming particularly pedant, let me know.. :-D

**Comment by paoloschi** [comment]
> If the CSV file is produced by code, we will also know the tag (such as in jgmenu-parse-ob.c before it started using ^pipe() last week).

To further clarify: by analyzing the description file, I easily get every "tag" value, surely.
What is missing from my head is: how can I know which of these was the last one opened in the previous jgmenu session? ..

**Comment by johanmalm** [comment]
You're English is fine. Don't worry about that. Also, no need to
apologise about being pedantic. I only do this for fun and I enjoy
getting the details right where I can. And it's great having you review
how the code works.

> This possibility caused my request to arise: when, later or tomorrow,
> I launch my application again, in case it would be profitable to
> reopen the menu directly at whatever level it was closed, how can
> I know the "tag" string value that I should pass to the "--checkout"
> option to obtain this?

I get it now. Here is my proposal: At exit, write the current tag name
to ~/.cache/jgmenu/tag_at_exit

I think ~/.cache... is better than /tmp... because
  - it is less likely to clash with other users on a multi-user system
  - it is more likely to be there next time you boot

There is a complication though, if a submenu is several levels
deep and we're calling new instances of jgmenu instead of using
^pipe(), we would you need to keep track of several exit tags. Also each
new instance would have to manage each own top-level "Back" doing
something like

`Back,jgmenu --simple --csv-file=foo --checkout=$(head ~/.cache/jgmenu/tag_at_exit -n1)`

> If I did "all items/group 1", coming back (the same if I had
> introduced a voice item 1,^back(item 1) at level 2) I would expect
> to find myself in the immediately preceding "group 1" sub-menu but
> now I'm transported to the "all items" sub-menu again (in the
> sequence, always returning to the first instance of "item 1" in the
> menu definition).

Yes. That's how it works. All 'tag' items are are put in a nodal tree
and have a parent (except the root-tag of course). Each 'tag' can only
have one parent. The ^back() command simply checks out that parent.

I did notice that you have two `^checkout(item 1)`. jgmenu won't stop
you doing this, but it's not designed to do anything intelligent with it
(open to suggestions as always).

> The second annotation on my specific example: you see that several
> times I have twice defined a same ^checkout() instance. for example,
> this way I got "item 1" both in the "all items" and in "group 1"
> sub-menues I wonder if there is no better way but this it looks good
> because so I just need to define "item 1 cmd 1" once for having it
> then whenever the "item 1" sub-menu appears: if "item 1" would
> contain hundreds of commands, it is really convenient..
> If I distinguish between the two "^checkout()", how can I then avoid
> defining the same "cmd" entries several times?

I think that a better way of dealing with this might be a filter.
We could do a ^filter() command :)
For example, if all the 'item 1' items contained a certain string
(e.g. __item 1__), we could simply search for it. You can play with it
by doing something like this. Then, simply type __item1__ when running
the menu.

`item 1,^tag(item 1)
item 1 cmd 1,command1 # __item1__
item 1 cmd 2,command2 # __item1__
item 1 cmd 3,command3 # __item1__`

**Comment by paoloschi** [comment]
> I get it now. Here is my proposal: At exit, write the current tag name
> to ~/.cache/jgmenu/tag_at_exit
> [..]
> There is a complication though, if a submenu is several levels
> deep and we're calling new instances of jgmenu instead of using
> ^pipe(), we would you need to keep track of several exit tags.

It is also true that of the usefulness of saving the tag, most of the time users (and even myself in other circumstances) could do without it, just as jgmenu works currently.
I wonder then if you have also considered such a solution:

    jgmenu --save-exit-tag=<file> ....

That is: jgmenu does nothing about saving the tag unless the user needs the specific function for that purpose.
If the user needs such a feature, he will choose the most convenient file location, taking care himself also of distinguish the tags from different sessions, and so on..
Does it make sense?

**Comment by johanmalm** [comment]
I think that's a good solution. I'll add it to the list.
We can add more sophistication later if we feel like it.

**Comment by paoloschi** [comment]
How beautiful!
About same "^checkout()" repeated and "go back" behaviors, I had not immediately considered that the introduction of the pipe functionality has already solved everything (as you explained to me above)!
According to my example, always defining different "^checkout(item ..)" values I will always have the "go back" result that I expect and, generating the "item .. cmd .." entries by a external script, in the CSV definition I will just have to repeat the "^pipe(my_script)" call a couple of times and not to repeat all the (potentially numerous) command items inside CSV, as I feared....
And with this, all the issues I have submitted are already brilliantly met! A thousand thanks!!

**Comment by johanmalm** [comment]
Sorry this has taken a long time.
jgmenu has become quite a different menu compared with when we had this discussion. Can I assume that this has been overtaken by events / no longer needed.
Please say if you still think that there is mileage in this. I’ll close for the time being.

**Comment by paoloschi** [comment]
Yes: "overtaken by events" AND "no longer needed" are both true so I agree with the closure.
Now I'll take advantage of this same login to ask a new question, in a new issue...
