### ISSUE TITLE
EDIT3: SIGABRT bug

### ISSUE THREAD

**Issue by paoloschi** [johanmalm/jgmenu#40]
(jgmenu v0.6.1-49-gd1d8)

I wonder if it is planned that the user will be able to configure between a self-opening of the next window and an opening that requires a click on the sub-menu entry...

very briefly, in the vast menu I'm defining I'm sure I would have a far better scrolling control if I could disable automatic opening....

**Comment by johanmalm** [comment]
I hadn't thought of it, but it's a good idea.
I've tried to make it respond to mouse events in a similar way to the Openbox menu, rather than GTK/Qt/etc menus which are all subtly different.
I'll gradually build in more options.
Will focus on releasing v0.7 first.

**Comment by paoloschi** [comment]
I try to better describe the difficulty I am encountering.
occurs only when a menu window cannot be entirely contained in the vertical space of the screen.
for example, the definition generated by this command line which consists of 100 pipe submenues in a single menu window:

```
for i in {1..100}; do echo "item ${i},^pipe(echo pipe ${i})"; done | jgmenu --vsimple
```

Once jgmenu has opened, I can scroll it from the first to 100th item with  [pag|arrow] UP | [pag|arrow] DOWN keys and, unless I press Enter or right arrow, no menu will open automatically.
But if, instead of using the keyboard, I grab my mouse now and try to scroll down using the fingerwheel, I find it hard to get beyond the 50th item because the submenus open automatically, the menu root loses the focus and so I no longer have any control, not even returning to the kbd..
When I manage to scroll down and display an item beyond the bottom edge of the screen, it quickly disappears again because the menu jumps up top again to match the submenu that has opened automatically..
I don't know if I have explained myself well and if maybe all this is happening only to me?

**Comment by johanmalm** [comment]
Okay. Thanks, I understand now. That's not right! In fact that's a bug.
I'll try to sort that ASAP.

**Comment by johanmalm** [comment]
I think these two commits fix the problem. I would be great if you could try it before I close the issue.

**Comment by paoloschi** [comment]
```
$ jgmenu --version
jgmenu v0.7.2-15-g351d
```
oh yeaah, I confirm that now with the fingerwheel I can scroll to the bottom despite the submenus are opening automatically. Great!
(I still remain of the idea that if the automatic opening could become optional would not be bad .....)

I'm noticing an odd behavior -don't know if related with the latest changes- by doing a 'fuzzy' filtering.
Running again the same example of the 100 pipe menus above, I pressed the '1' key: the filtering of the elements is correct however, trying to open a submenu, I only see a white rectangle flashing very briefly and, if I had chosen an item other than 'item 1', after the flashing the selection in the root menu jumps immediately to 'item 1'..
In this situation, pressing Esc will return all operation to normal again, with the submenus that open correctly.
can you reproduce the 'fuzzy' behaviour I have described?
if already known and/or unrelated, this issue can be closed here even for me

(the other effect that I observe but that I know to be known and in discussion, is the disappearance of the mouse cursor outside the menu window: it does so also here: xorg-minimal-1.2 without personalized _xorg.conf_, xorg-server-1.19.5, openbox-3.6.1  without compositing additions, xf86-video-intel-2.99.917.56, ..? )

**Comment by johanmalm** [comment]
Thanks. You're a good tester! ^checkout() and ^back() items were previously excluded from the search.
I've not also excluded ^pipe() items.
We could consider a more sophisticated search later, but I want to keep it bug free and clean for the time being.

Regarding the disappearing pointer, I'm struggling to work out what's causing it. I've changed the issue status to "help needed" - so if you've got any ideas :)

Okay. Happy to add config option to control auto/manual submenu opening on hover - but might just park it for the time being.

**Comment by paoloschi** [comment]
As the issue remains open for the new purpose, I would like to clarify why I have asked for..

If I had conceived to use jgmenu for the sole purpose of making the menu desktop, I wouldn't have thought about the need to have the submenus that open only after a click!
Instead, I'm having a lot of fun (and profitably!) building 'real applications' in bash + jgmenu as an interface!
I am at a good stage in interfacing with TvHeadend local sever and I already use a streaming website via Rest API and jgmenu to choose and put videos into play much better than from the webpage!..
(but it is only sw by a  self-taught amateur, badly written and not good enough to be shared... good barely for me...)

I told you all this so it becomes clear why the automatic opening becomes for me a small hitch: I have pipe submenus populated on the fly with the results of API requests whenever they open, ergo every time a submenu opens and I don't need it, it is all network traffic that I am forced to generate unnecessarily (through my narrow-band ADSL).
Nothing more than this and, as you can see, nothing that requires any true urgency: the fun is not affected! :-)

(but how much I chatter!... I hope at least that this exercise can improve my English!)

**Comment by johanmalm** [comment]
Thanks for the background :) It's great that you're hacking around with it. That's what I intended it to be for.
Check out the latest commit. I think I've done it.
Set `sub_hover_action = 0` in jgmenurc

Just for you!

**Comment by paoloschi** [comment]
works perfectly! How to thank you?
that "Only for you!" it is a little embarrassing for me so I hope other users can find this new option useful! 

There is a behavior that I am observing that I imagine is due only to the incompleteness of the "work in progress" ....but I'm curious:
In the root of my menu I have defined some images.
I know that "load icons for pipes" is in the TODO list.
currently:
- I have opened the root menu (and I see all images)
- I'm hover to a pipe submenu and now I click on it (submenu has opened)

__1th behavior__: now I press the right button WITHOUT MOVING the mouse:

- jgmenu exits with code 134 (134 - 128 = 6; signal 6 is SIGABRT and so it seems that this signal is being sent)

__2th behavior__: now BEFORE to press the right button I MOVE the mouse and (even if I'm still highlighting the same menu item):

- all images which I was seeing in root menu immediately disappear
- as long as the pointer is above the menu, pressing the right button from this point in time does not generate any action (nor a SIGABRT)

I have no requests about these behaviours (which are certainly already known to you)
to be taken just like more feedback :-)

**Comment by paoloschi** [comment]
That's what I found so far:
here is the exact paste of a submenu item definition row generated by a my piped script and that produces the 1th behavior I have described for which jgmenu closes by a SIGABRT

```
"""topcrime""","""echo -e "ch_name='topcrime'\nch_uuid='f4f53ba28782a91fd3d0a6c7c5ee17f8'\nch_picon='xmap-3838.png'" >/tmp/1000-sintonie/etc/PLUGIN/tvheadend/current/stream && /opt/sintonie/PLUGIN/tvheadend/go_streaming""",/tmp/1000-sintonie/PLUGIN/tvheadend/xmap-3838.png
```

in the command field I execute 2 actions: first I write some data in a file to be sourced later && then I run another script...
in a precautionary excess, I have enclosed both the definition and the command fields in the triple quotation marks 

I'm noting this:
- if I remove the triple quotation marks from the command field nothing changes = jgmenu closes with exit code 134
- Now I put the quotation marks back again to the command field and this time I remove them from the description field: jgmenu no longer closes! not more exit code 134

digging with my experiments, I marginally also found this:

```
echo "item,echo -e \"name='a string\nid=1234\" >/tmp/testfile" | jgmenu --vsimple
```

the command execute the internal Bash "echo" to generate a multi-row file; but the result is:

```
$ cat /tmp/testfile
-e name=a stringnid=1234
```

???
repeating with /usr/bin/echo instead

```
echo "item,/usr/bin/echo -e \"name='a string\nid=1234\" >/tmp/testfile" | jgmenu --vsimple
```

the contents of the file are now correct

```
$ cat /tmp/testfile
name='a string
id=1234
```

**Comment by johanmalm** [comment]
Paoloschi. Interesting. You really are a good tester :)

I've just pushed a commit which fixes a bug I've just discovered (after reading your post). It wasn't specific to pipemenus, but only manifested itself when using pipes. Has that fixed your crash?

You have to be careful when using ^pipe(). The inner value will be executed in a shell. jgmenu will then try to parse the output as CSV. I haven't tried to protect from bad data - as it's not easy.

I'll take a look at the icons. I had not seen that behaviour before, but have been able to re-produce it.

**Comment by paoloschi** [comment]
```
$ jgmenu --version
jgmenu v0.7.3
```

I have "exit 134" as before.
but it will be useful to warn me to pay attention to the commands executed via pipe!
I will examine each alternative syntax before considering that it may be a jgmenu bug......

**Comment by johanmalm** [comment]
Could you check if you still get the icon and SIGABRT issues.

I'm pretty sure I've fixed the icon issue when opening pipemenes.

I'm not sure about the SIGABRT. If you still get it, could you help me replicate it.

**Comment by paoloschi** [comment]
```
$ jgmenu --version
jgmenu v0.7.3-3-g0548
```
I can confirm that the icon issue __is fixed__!
on my SIGABRT issue..

I have already reported that I can avoid crashes by removing the triple quotation from the description field of the jgmenu definition that I'm developing for my project.
Now I tried to make the problem more easily reproducible by reworking the example '__ex05__' taken from jgmenu sources.
First of all I tested the original example well, controlling it from both mouse and keyboard: it works perfectly here too!
afterwards, I've edited the `ex05/pipe2.csv` file to repeat the same condition I've in the definition of my project and that is, I've simply enclosed the description field of line 3 in the triple quotation marks, this way:

```
this is pipe2
list files in current directory,^pipe(ls -1)
"""list pixmaps using triple quote""","""^pipe(find /usr/share/pixmaps -type f -printf '%f,display %p,%p\n')"""
```

and that's what happens to me..
By acting through mouse, everything continues to work perfectly: never a SIGABRT.
But by acting via the keyboard ...bingo!

- run `ex05.sh` and move the __down__ and __right__ arrow keys until the pipe2 menu appears
- go back to parent by pressing __left__ arrow button only once

et voilà:

```
$ ./ex05.sh
info: got font from gtk config file
info: set font to 'Fira Sans 10'
info: got icon theme from gtk config file
info: set icon theme to 'gnome-wine'
*** Error in `jgmenu': free(): invalid pointer: 0x00005626c83de323 ***
Aborted

$ echo $?
134
```
..and same behavior by placing quotation marks in line 2 instead of line 3 or also by adding them to the `ex05/pipe1.csv` file, provided that they are applied to the description field; adding them to the command field never cause the issue.
It's not clear to me why I can reproduce from my project both working from keyboard and mouse while with `ex05` the right mouse button doesn't lead to the crash here but if you can reproduce the thing as I have reported here, I believe there will be a single solution to the whole issue : -)

**Comment by johanmalm** [comment]
No1 tester! Thanks for the detail.
You led me straight to the bug. Perfect.
I'm nearly pressing the "close issue" button, but won't until you confirm the bug is gone.

**Comment by johanmalm** [comment]
P.S. I've done a lot of re-factoring over the last couple of months which is why these types of bugs creep in. Hopefully we'll soon iron them out.

**Comment by paoloschi** [comment]
```
$ jgmenu --version
jgmenu v0.7.3-4-gc418
```
no doubt: __SIGABRT is gone__ here too, even playing with mouse on my building project!! Yeyeah!!

However.. while on the keyboard everything is perfect, tinkering with the mouse I see now that I can provoke a __exit code 1__..
it's a completely different matter that I think is better to discuss elsewhere so for a few seconds please enjoy all the satisfaction of pressing the 'Close' button 'cause I am about to open a new isse ;-)

**Comment by johanmalm** [comment]
Thanks. This was a good thread! Sorted lots of bugs.
