### ISSUE TITLE
Disappeared window name, set class name and instance

### ISSUE THREAD

**Issue by subnixr** [johanmalm/jgmenu#42]
With the recent updates jgmenu doesn't seem to set it's window name anymore.
I was using that property to exclude its instances from some compton configurations (namely: `focus-exclude = ["name = 'jgmenu'"];`).

It also would be handy to have a properly class name and class instance (`WM_CLASS` property) set on the window, for the same reason above.

**Comment by johanmalm** [comment]
Hi @subnixr. Thanks for the feedback.
I commented out the WM_NAME code during the multi-win re-write. Sorry. I've now reinstated it.
I have also set WM_CLASS to 'jgmenu' - great idea.
I do run compton, but don't know it well. Either of these work for me now:
[code]shadow-exclude = [ "name = 'jgmenu'" ];[/code]
[code]shadow-exclude = [ "class_g = 'jgmenu'" ];[/code]

Please shout if I've misunderstood something.
Do you want me to upversion, or do you just build it from the gitrepo?

**Comment by subnixr** [comment]
> Please shout if I've misunderstood something.

You got everithing right, thanks!

> Do you want me to upversion, or do you just build it from the gitrepo?

I usually build it from the [AUR package](https://aur.archlinux.org/packages/jgmenu/), but it's no problem to clone the repo and build manually. Do what you think it's best :)

**Comment by johanmalm** [comment]
Super. Thanks.
I'll do another release soon - but have a few other niggles that I want to sort first. I know numbers are free, but don't want to go too crazy.
