### ISSUE TITLE
Dual Screen

### ISSUE THREAD

**Issue by Dobbie03** [johanmalm/jgmenu#43]
Loving jgmenu, I have two monitors and I have played around with the x/y axis to get the positioning of the menu when I open it from polybar, but I can seem to get it to open on the right hand screen where the launcher for jgmenu is.

Is there something I am missing here?

**Comment by Dobbie03** [comment]
Worked it out.  I removed the menu_halign which prevented the x/y doing what I wanted.

Sorry for wasting time.

**Comment by johanmalm** [comment]
Glad you worked it out.
I rarely use more than one screen, so do say if there is anything that can be done better.

**Comment by Dobbie03** [comment]
If you could incorporate anoption to explicitly mention a monitor, that would be awesome.

**Comment by johanmalm** [comment]
It's not immediately obvious to me how to do this. I'll have to do some research.
What's the reason? Is it to "select" the monitor when using a keyboard short-cut. Does it work properly when using a mouse?
I'll re-open the issue so I don't forget.

**Comment by Dobbie03** [comment]
I just thought it would be easier if you could have a section to place the menu on a certain monitor while keeping the x/y settings for further customisation.

I managed to get the menu to open on the monitor I wanted but when scrolling through the menu the menus would open on the other monitor.  Here is a screen recorder to show:

https://youtu.be/bd4UpVKbObU

Obviously where the polybar starts is the second monitor.

**Comment by johanmalm** [comment]
Okay. Understand.
That looks like a bug. I'll need to do the following for multi-screen:
  - sort out positioning of submenus
  - handle positioning when jgmenu is called by keyboard shortcuts

**Comment by johanmalm** [comment]
I think that fixes it. The menu now starts on the monitor where the pointer is.
I can easily add a config option to specify the screen number if that's useful.

**Comment by Vladimir-csp** [comment]
This option could be the same style as 'primaryMonitor' in the openbox configuration:

> ...It can be an index from 1, specifying a particular monitor.  Or it can be one of the following: 'Mouse' - where the mouse is, or 'Active' - where the active window is.

Also in randr certain monitor can be marked as primary, but configuration without primary monitor is also valid.

**Comment by johanmalm** [comment]
Yes. Good idea.

**Comment by johanmalm** [comment]
I've had a more serious attempt at sorting out multi-monitor support. Appreciate any testing.
Will add a config option.

**Comment by johanmalm** [comment]
Matt, Vladimir - I think this is done now. I'll close the issue, but please shout if there is anything I've missed.

**Comment by Dobbie03** [comment]
I haven't had a chance to test this, will check it out very soon.

Thanks for the update

**Comment by johanmalm** [comment]
@Dobbie03 This is probably obvious to you, but writing it just in case. The easiest way to test is like this:
`make prefix=$HOME install` provided you have $HOME/bin in your $PATH
You can then uninstall it with `./scripts/uninstall.sh`
