### ISSUE TITLE
issue "fatal: badness: ui_win_activate"

### ISSUE THREAD

**Issue by paoloschi** [johanmalm/jgmenu#44]
```
$ jgmenu --version
jgmenu v0.7.3-4-gc418
```
The menu of __ex05__ example is opened as in the snapshoot

![jgmenu_01](https://user-images.githubusercontent.com/14022008/32698734-9963f372-c7aa-11e7-9888-1c5c6985cae1.png)

every action performed by keyboard is regular.
via mouse, if I have my pointer over the central submenu and I press the right button, I get this 

![jgmenu_02](https://user-images.githubusercontent.com/14022008/32698739-ab27ad1a-c7aa-11e7-803a-636b5e96dfcc.png)

is a condition this one you cannot have via keyboard and, logically speaking: when a submenu has been closed, should not also close all related beneath sublevels?? (..)
Apart from the consideration above -in the situation of the second snapshoot- if I now move my mouse to the right, as soon as the pointer is over the _pipe2_ submenu..

```
$ ./ex05.sh
info: got font from gtk config file
info: set font to 'Fira Sans 10'
info: got icon theme from gtk config file
info: set icon theme to 'gnome-wine'
fatal: badness: ui_win_activate
info: cleaning up...

$ echo $?
1
```

**Comment by johanmalm** [comment]
Thanks

I have disabled right-click in multi-window mode. I doesn't really make sense anyway.

I will re-factor checkout_parent() at some point, but it needs a bit more thought. Have added it to my TODO file.
