### ISSUE TITLE
Menu does not launch

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#46]
Menu fails to launch by `jgmenu_run lx`, with current git state and this config:
```
stay_alive	= 0
at_pointer	= 1
font_fallback = xgt
icon_theme_fallback = xgt
```

Output:
```
info: parsing lxqt-applications.menu
info: using config file /etc/xdg/jgmenu/jgmenurc
warn: NULL passed to sbuf_addstr
warn: NULL passed to sbuf_addstr
warn: NULL passed to sbuf_addstr
warn: NULL passed to sbuf_addstr
info: parsing tint2 config file '/home/username/.config/tint2/tint2rc'
info: got font from gtk config file
info: set font to 'Sans 10'
info: got icon theme from gtk config file
info: set icon theme to 'Vivacious-Dark-Graphite'
sh: 1: pmenu: not found
fatal: input file contains no menu items
```
Also I have a user-level config (identical to the global one, testing leftovers), but it isn't mentioned in the output.

**Comment by johanmalm** [comment]
@Vladimir-csp Thank you. Apologies for breaking things.

I'm in the middle of changing the CLI with a view to a) simplify, b) increase consistency and c) remove some old "relics" from the early days. It's going to be a series of commits including updates to the documentation, but it will probably take me 1-2 weeks. I should probably add a Makefile message to make this clear.

One of the things I'm doing is to phase out the syntax `jgmenu_run [lx|xdg|pmenu|ob]` as I think it's cleaner to just set csv_cmd in jgmenurc to lx, etc. The --csv-cmd option will remain.

I just pushed a couple of commits from Sunday. Those might help. If not, if you're happy to just set the csv_cmd variable in jgmenurc for the time being, that would be great.

Regarding your user-level config, I'm not sure what going on with that. I've just tried on mine and it reads $HOME/.config/jgmenu/jgmenurc in preference to /etc/xdg...
Have you got any unusual XDG_CONFIG_* environment variable settings?

I'm not sure what's going on with the warning (NULL passed to sbuf_addstr).
Have you had those before?
I can't reproduce them, so anything you could do to help would be great.
I guess from printf debugging in jgmenu.c lines 2122-2139 would be a senible place to start.

Many thanks

**Comment by johanmalm** [comment]
Makefile warning added.

**Comment by johanmalm** [comment]
v0.7.6 released.
See release notes on new CLI.
Please shout if you still have the user config issue. I can't reproduce it.

**Comment by Vladimir-csp** [comment]
With current jgmenu piping does not work:
```
$ echo Test | jgmenu
info: using config file /home/username/.config/jgmenu/jgmenurc
info: parsing tint2 config file '/home/username/.config/tint2/tint2rc'
info: got font from tint2rc
info: set font to 'Liberation Sans 10'
info: got icon theme from tint2rc
info: set icon theme to 'Vivacious-NonMono-Dark-Graphite'
Traceback (most recent call last):
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 446, in <module>
    main()
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 443, in main
    create_menu(append_file, prepend_file)
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 389, in create_menu
    tree, categories = load_applications()
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 346, in load_applications
    entry = read_desktop_entry(os.path.join(dirpath, filename))
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 220, in read_desktop_entry
    lines = f.read().split("\n")
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 78: invalid start byte
Badness in build_tree() at jgmenu.c:1036
```

But `--csv-cmd` does work:
```
$ jgmenu --csv-cmd='echo Test'
info: using config file /home/username/.config/jgmenu/jgmenurc
info: parsing tint2 config file '/home/username/.config/tint2/tint2rc'
info: got font from gtk config file
info: set font to 'Sans 10'
info: got icon theme from gtk config file
info: set icon theme to 'Vivacious-Dark-Graphite'
info: cleaning up...
```

**Comment by johanmalm** [comment]
Thanks for the feedback. I'll break it down into two chunks:

1. Yes. We don't read stdin by default anymore. See third bullet in [v0.7.6 release notes](https://github.com/johanmalm/jgmenu/blob/master/docs/relnotes/0.7.6.txt)
I really don't like changing the command line interface, but figured it was better to do it all in one hit. Considering we're still a way off v1.0, I thought it was best to just get on with it. Apologies if it's caused any issues.

2. It looks like we have a pmenu bug - possibly UTF-8 related. Would appreciate if you could supply the following:

- What's your $LANG?
- Run `jgmenu_run pmenu` and paste the output.
- Depending on where the above stops, it might point us to a specific .desktop or .directory file that we fail to handle correctly. If there is a "problem" file (not that it's the fault of the file), it would be useful to get a copy of it too.

You're appear pretty experienced at this :) Anything your intuition tells you would be useful too.

**Comment by Vladimir-csp** [comment]
```
$ echo $LANG
ru_RU.UTF-8
$ jgmenu_run pmenu
jgmenu,^tag(pmenu)
Traceback (most recent call last):
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 446, in <module>
    main()
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 443, in main
    create_menu(append_file, prepend_file)
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 389, in create_menu
    tree, categories = load_applications()
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 346, in load_applications
    entry = read_desktop_entry(os.path.join(dirpath, filename))
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 220, in read_desktop_entry
    lines = f.read().split("\n")
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 78: invalid start byte
```
Same thing with LANG=C
I added `print(path)` to `read_desktop_entry` function. It seems to stop on extace.desktop

[extace.desktop.zip](https://github.com/johanmalm/jgmenu/files/1590405/extace.desktop.zip)

**Comment by Vladimir-csp** [comment]
LANG: ru_RU.UTF-8
Same happens with LANG=C
I've added `print(path)` to `read_desktop_entry`. It seems to stop on extace.desktop
[extace.desktop.zip](https://github.com/johanmalm/jgmenu/files/1590414/extace.desktop.zip)

**Comment by johanmalm** [comment]
The file is ISO-8859-1 (Latin1), hence the error. Freedesktop specifies they should be UTF-8.

Do file -i extace.desktop to check.

Unicode presents a number of problems:
- not portable
- although this issues relates to python, it's worth noting that it’s not compatible with normal C "string" functions either
- we don't like text with embedded zero bytes (not just me :))

Suggest we leave it as a warning rather than trying to decode Unicode

**Comment by Vladimir-csp** [comment]
I do not think that an error in reading a desktop entry should cause overall failure. Just print an error to stderr, skip the problematic entry and continue.

**Comment by johanmalm** [comment]
Great minds think alike. That's exactly what I have done. See commit f176483
Sorry, should have made last sentence in previous post a bit clearer.

**Comment by Vladimir-csp** [comment]
I have another problematic entry which is a dead symlink (weird packaging from third-party vendor), so `read_desktop_entry` fails at `open` stage. Perhaps `try` should be moved up a bit.

**Comment by johanmalm** [comment]
Implemented. I think that makes for better code.
