### ISSUE TITLE
Support Path key

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#49]
Currently `Path` is ignored and all applications are launched in home directory.

**Comment by johanmalm** [comment]
Please could you explain further.

If you do
`cd ~/foo
jgmenu`

and then click on a terminal, it will start $PWD will be "~/foo"

**Comment by Vladimir-csp** [comment]
I mean the `Path` key in the desktop entry.

**Comment by johanmalm** [comment]
Sorry. Understand now.
It looks like libmenu-cache has a `menu_cache_app_get_working_dir()` so that should work.
How do you suggest I implement? Just let jgmenu-lx output `cd $working_dir; $command` in the second field?

**Comment by Vladimir-csp** [comment]
It's up to you. If it won't cause any trouble with `Exec=sh -c "some commands"` style of entries, then yes. I presume, the alternative would be changing input format?

BTW, what if `Exec=` has commas in it?

**Comment by johanmalm** [comment]
No need for sh -c...
[https://github.com/johanmalm/jgmenu/blob/master/util.c#L73](https://github.com/johanmalm/jgmenu/blob/master/util.c#L73)

**Comment by johanmalm** [comment]
Good point ref commas. I think it's highly unlikely that the `Exec=` value will have commas - but you never know. If could check for commas, and if they exist, wrap the command in triple quotes.

**Comment by Vladimir-csp** [comment]
Desktop entry's `Exec=` is a pretty strict thing, it isn't supposed to be a shell line. It is a command with optional arguments optionally marked by double quotes only. Therefore `sh -c "command > file"` or `env VAR=something command` is used whenever there is a need to cram put something more complex into an entry.

**Comment by Vladimir-csp** [comment]
There may be a need to change input format after all.

**Comment by johanmalm** [comment]
^^ Understand
^ Sure. I'm not adverse to that at all. We might need a field for `Comment=` too. And I had though of a field for "meta" data to enable more sophisticated filtering options.

**Comment by johanmalm** [comment]
How about adding three fields so that it looks like this:

1. name
2. command
3. icon
4. comment (for pop up or item spanning two lines - e.g. comment in smaller font underneath name)
5. working directory (start in $HOME if not specified)
6. "meta data" to enable more sophisticated filtering (e.g. "categories")

If "command" is prepended by @, do not use sh -c '' wrapper in spawn(). This way we remain backward compatible, but enable XDG spec adherence (and cut out unecessary shell invokation)

@o9000 any thoughts welcome to keep us on the straight and narrows here.

**Comment by Vladimir-csp** [comment]
Sounds good.
Have you decided how to handle commas?

**Comment by johanmalm** [comment]
Yes. If comma exists, wrap in  triple quote.
If command and """ exist, we can't do it :-)

**Comment by Vladimir-csp** [comment]
Hi
Any news on this? It would be really nice to have less hassle with WINE apps (which rely on Path= key to correctly set up prefix executions)

**Comment by johanmalm** [comment]
I'll focus on this over the next few weeks.
I've worked "ob" for a while and will upversion very shortly.
It feels like it's lx next - and the additional fields as specified above.

**Comment by johanmalm** [comment]
I think this done now with the exception of removing the 'sh -c' construct in spawn() (which I have added to the wiki Roadmap because it needs a bit of work).
Any testing appreciated.
I'll close issue unless you have any issues.

**Comment by Vladimir-csp** [comment]
Cool, it works. 
Found another problem...
