### ISSUE TITLE
Icons?

### ISSUE THREAD

**Issue by o9000** [johanmalm/jgmenu#5]
Would it be possible to show icons for menu items?

P.S. I'm opening all these issues as I am trying to find a simple start menu implementation, that does not depend on GTK, nor openbox, that can be used easily with tint2. Yours looks nice and the code is very simple :)

**Comment by johanmalm** [comment]
Nearly there. I've just got a bit more tidying up to do with icon-find.c and xdgdirs.c.
Should be able to commit at the end of this week.
Thanks for your help to get this far.

**Comment by johanmalm** [comment]
I'm happy that icons are working okay now.
I will do something later for xpm icons to avoid the GTK dependency.
