### ISSUE TITLE
In bspwm, the menu goes behind other windows

### ISSUE THREAD

**Issue by johanmalm** [johanmalm/jgmenu#51]
In bspwm, the menu goes behind other windows
Raised by @head-on-a-stick in this thread:
[https://forums.bunsenlabs.org/viewtopic.php?id=4605](https://forums.bunsenlabs.org/viewtopic.php?id=4605)

**Comment by Head-on-a-Stick** [comment]
Update: when the bspwm desktop starts the tint2 launcher works fine with the menu appearing in front of any opened applications, as expected.

However, if conky is restarted then the issue starts and the menu subsequently appears behind any opened windows with a restart required to fix things.

This is the only way I can reproduce the problem at the moment, until conky is restarted jgmenu works fine.

**Comment by johanmalm** [comment]
^ Thanks. I can re-produce it now.
My guess is that the "stacking order" is set by the order in which programs are started and that XRaiseWindow() and similar have no effect on it. This probably makes sense in a tiling manager.
If jgmenu is started first (in stay-alive mode) then it appears behind other windows (which were started/opened later).

**Comment by johanmalm** [comment]
@Head-on-a-Stick Does this help? I was able to reproduce it on both dwm and bspwm. This fixes it for me.

**Comment by Head-on-a-Stick** [comment]
Sorry but I can't get the latest version to build in either Debian stable or Alpine Linux edge, this is the error:

````
jgmenu-lx.c: In function 'process_app':
jgmenu-lx.c:85:4: warning: implicit declaration of function 'menu_cache_app_get_generic_name' [-Wimplicit-function-declaration]
    menu_cache_app_get_generic_name(MENU_CACHE_APP(app)));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
jgmenu-lx.c:85:4: warning: passing argument 3 of 'fmt_name' makes pointer from integer without a cast [-Wint-conversion]
In file included from jgmenu-lx.c:13:0:
fmt.h:6:6: note: expected 'const char *' but argument is of type 'int'
 void fmt_name(struct sbuf *buf, const char *name, const char *generic_name);
      ^~~~~~~~
     CC    fmt.o
     LINK  jgmenu-lx
jgmenu-lx.o: In function `process_app':
/home/empty/git/jgmenu/jgmenu-lx.c:85: undefined reference to `menu_cache_app_get_generic_name'
collect2: error: ld returned 1 exit status
make: *** [Makefile:55: jgmenu-lx] Error 1
````

The error status is 2.

What have I done wrong?

**Comment by johanmalm** [comment]
Sorry. I need to add a note in the README.md.

lx now relies a recent version of libmenu-cache.

On BunsenLabs, do

`make NO_LX=1 install`

**Comment by Head-on-a-Stick** [comment]
OK, that fixes the problem.

Well done sir!

**Comment by johanmalm** [comment]
Excellent.
For completeness:
[https://github.com/johanmalm/jgmenu/blob/master/Makefile#L9](https://github.com/johanmalm/jgmenu/blob/master/Makefile#L9)

Also, I've just added a note in [INSTALL.md](https://github.com/johanmalm/jgmenu/blob/master/INSTALL.md)
