### ISSUE TITLE
Menu not launching at pointer position in multiple monitor setup

### ISSUE THREAD

**Issue by maqwqa** [johanmalm/jgmenu#56]
When I use 3 monitor setup, menu is launching at the vertical center instead of being at pointer position - when opening menu (with `--at-pointer` option) from the bottom edge of the screen.

This only occurs for second and third monitor. For the first one (DP2) menu is placed correctly near the bottom edge (when pointer is there).

![monitor_layout](https://user-images.githubusercontent.com/11500801/39092794-8cbc17be-4615-11e8-9c23-63c853d3f3b5.png)
```
xrandr
--output DP2 --mode 1920x1080 --pos 0x0 --rotate right
--output DP1 --mode 1920x1200 --pos 1080x544 --rotate normal
--output DVI-I-1-1 --mode 1920x1080 --pos 3000x544 --rotate normal
```

Tested with jgmenu v0.8.2.

BTW: thanks for sharing useful software!

**Comment by johanmalm** [comment]
Thanks for reporting. I'll have a look as soon as I can.

**Comment by johanmalm** [comment]
I can't replicate.

What Window Manager do you run?
Do you run a panel? If so, which?

Would you be able to do the following:

  - Run without a panel to see if that makes a difference (e.g. killall tint2 ; killall polybar)

  - Run without a jgmenurc, to see if the bug is present with default config values.

  - I'm wonder if it's related to _NET_WORKAREA
    If you're happy to compile jgmenu, could you try to comment out workarea_set_margin() and 
workarea_set_panel_pos() in jgmenu.c
    [https://github.com/johanmalm/jgmenu/blob/master/jgmenu.c#L2205](https://github.com/johanmalm/jgmenu/blob/master/jgmenu.c#L2205)
    There are step-by-step instructions in [https://github.com/johanmalm/jgmenu/blob/master/INSTALL.md](INSTALL.md)

Grateful for any help you can give in tracking down this bug.

**Comment by johanmalm** [comment]
I think I get it now.
It's what we introduced here: [https://github.com/johanmalm/jgmenu/commit/0c4f42bfc14922fc6ab44802bf0abf2fef2914bd](https://github.com/johanmalm/jgmenu/commit/0c4f42bfc14922fc6ab44802bf0abf2fef2914bd)

At "at_pointer" mode, we respect the workarea (if we can guess it). It assumes that the same "panels/docks" exist on the other monitors.

Have you just got a panel/dock on one monitor?

I'm tempted to revert it and just let jgmenu behave like the openbox menu. I will give it some thought though.

**Comment by johanmalm** [comment]
I believe it's fixed, so will close the issue. Please shout if it still manifests itself.
