### ISSUE TITLE
Add config options for menu height

### ISSUE THREAD

**Issue by vaygr** [johanmalm/jgmenu#57]
This is just a feature request from [this discussion](https://github.com/johanmalm/jgmenu/commit/0420ea6974a9c662ebb3b8efca0561c907f7d251).

**Comment by johanmalm** [comment]
Hi
Thanks for logging this.
I'm just about to release v1.0
Will have a look at ^root() markup after that. It should behave like single
window mode, will will allow cleaner code.
Johan

**Comment by vaygr** [comment]
Highly appreciate it @johanmalm !

**Comment by johanmalm** [comment]
It's starting to take shape.

If you're happy to build it yourself, try with

hide_back_items = 0
csv_single_window = 1

If you run `jgmenu init`, these to option will be added. You can then just edit to suit.

**Comment by johanmalm** [comment]
![single_window](https://user-images.githubusercontent.com/6955353/42337944-246f65d0-8080-11e8-8319-7bc1a3b7abc5.gif)

**Comment by vaygr** [comment]
Thanks! I tried version 1.1.

For some reason I can see only 1 element + back button in the menu. Has the syntax been changed a bit? E.g.:

```
Command0,command0
Sub,^root(sub)
Sub,^tag(sub)
⇠,^back()
Command1,command1
Command2,command2
Command3,command3
```

So I can see only `Command1` and back button in the submenu.

**Comment by johanmalm** [comment]
I'm thinking of adding two config options: `menu_height` and `menu_height_mode`

menu_height_mode = static-min | dynamic-min | fixed

**static-min**
This is the default and is backward compatible.

'static' means that the height of the initial root menu will be used
and that this will never change.

'min' means that the menu height will be calculated based on the
height of the all items in it, but will never be less than
menu_height.

**dynamic-min**

As static-min, but the menu height will be re-calculated every time
the root menu is redefined using ^root().

This could work well with

    hide_back_items     = 0
    csv_single_window   = 1

**fixed**

'fixed' means that the height will be set to menu_height.

**Comment by vaygr** [comment]
Yeah, that sounds good.

**Comment by johanmalm** [comment]
Appreciate any feedback on the new options.

**Comment by vaygr** [comment]
Hmm, just tested the latest from `master`, can see only `Command1` from the example above.

**Comment by vaygr** [comment]
Oh, I apologize, I used `dynamic-min` from the example and missed it in the code.

Yes, `dynamic` works, sorry for the noise.

**Comment by johanmalm** [comment]
Glad it’s working.
