### ISSUE TITLE
Account for long labels while searching

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#59]
When search in applications is performed, menu width stays constant and text from long labels is cut uncleanly.
Solution would be to either cut text properly inside menu item boundaries with some visual indications of the cut, or to change menu width based on current search results.

**Comment by johanmalm** [comment]
Good idea.
We should definitely do this.
It's not immediately obvious to me how to implement this, but I will explore the limits of some pango functions.

**Comment by johanmalm** [comment]
Done. Should have done that ages ago 😀
