### ISSUE TITLE
jgmenu doesn't work on X without Xinerama support

### ISSUE THREAD

**Issue by vaygr** [johanmalm/jgmenu#61]
I had to switch to a newer version of the intel graphics driver, which no longer supports Xinerama extension. Thus made jgmenu crashing for me:

```
Xlib:  extension "XINERAMA" missing on display ":0.1".
Badness in ui_get_screen_res() at x11-ui.c:158
Segmentation fault
```

It seems the only call is `XineramaQueryScreens()`. Is it something that can be replaced with XRandr-like?

**Comment by johanmalm** [comment]
That sounds like a good idea.
I’ll try it at the weekend.

**Comment by vaygr** [comment]
Yeah, that or like plain X calls. Thanks!

**Comment by johanmalm** [comment]
I've replaced xinerama with xrandr on branch 'dev'
I've tested it on my machine, but but would be grateful if you could test it too before I push it to the 'master' branch.

```
git clone -b dev https://github.com/johanmalm/jgmenu
cd jgmenu
make
killall jgmenu
JGMENU_SCREEN_INFO=1 ./jgmenu
```
Press F10 to exit jgmenu
Move pointer to a different monitor

```
JGMENU_SCREEN_INFO=1 ./jgmenu
```

**Comment by vaygr** [comment]
Fantastic job, works like a charm! I'm assuming it's easy to port to 0.8, while I'm waiting for the `menu_height` setting as per https://github.com/johanmalm/jgmenu/issues/57#issuecomment-403237755.

**Comment by johanmalm** [comment]
Yes, x11-ui.c has not changed much for a long time, so should be easy to back-fit.
I’ll try to get 57 done though.
