### ISSUE TITLE
Using Tab key to cycle through results

### ISSUE THREAD

**Issue by anhthii** [johanmalm/jgmenu#63]
I'm wonder if there is a feature like using Tab to cycle through results like Rofi menu. I'm searching for a way to configure this but can't find one yet. Thank you for any suggestions

**Comment by johanmalm** [comment]
No. Currently, you can only move between items using up/down/pgup/pgdn/home/end.

I'm intending to use tab for moving between widgets and menu items, and anticipate that this will be implemented over the next couple of months.

We could consider supporting custom key-mapping, but I don't envisage implementing that in the very near future.

**Comment by anhthii** [comment]
yes just close it.
