### ISSUE TITLE
Introduction of pango markup for the separator seems to involve even normal items (?)

### ISSUE THREAD

**Issue by paoloschi** [johanmalm/jgmenu#64]
I have some bash scripts that have been working well for a long time now using jgmenu as an interface for TVHeadend (...)
After the introduction of "sep_markup =" I began to see results like this:

![snapshoot](https://user-images.githubusercontent.com/14022008/47845378-22fb7200-ddc5-11e8-86b4-2b3d3a079360.png)

The rightmost submenu is a pipe() menu and shows a list of EPG events.
When the title of an event contains a special HTML character (in this case they are '&'), the text disappears as you can see.
This makes me think that Pango is now interpreting not only text in sep() entries... Is that so?
...'cause if I do escaping all of `&` as `&amp;` when I extract the string values from the JSON document, I regain that jgmenu show me all the entries otherwise missing

I would therefore like to understand if this is a PANGO side effect introduction or an intentional innovation so that now it's up to me to adapt all the scripts that I've done so far...

Thanks and congratulations @johanmalm for this increasingly valuable powerful tool!

**Comment by paoloschi** [comment]
Having now the certainty that adapting my scripts by escaping special characters is the right action to take, I'll be happy to do it.
So, please: do not modify your development plans for this little inconvenience!!!!
(is solved for me, shall we close?)

**Comment by johanmalm** [comment]
That's great.
Hopefully it won't apply to many users.
Great to see that you're still active.
I'll close.
