### ISSUE TITLE
String after percent sign is cut

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#68]
While testing, I've put this line:
```
Exec=sh -c "date +%%T > foo"
```
According to desktop entry spec, this is the proper way to escape `%`, but instead the string is cut:
```
$ jgmenu_run lx | grep date
Path test,sh -c "date +,terminal,/tmp/test dir
```

**Comment by johanmalm** [comment]
That's great feedback. Aim to get 100% XDG compliant, so need to handle %-stuff properly.

Have added to [Roadmap](https://github.com/johanmalm/jgmenu/wiki/Roadmap)
