### ISSUE TITLE
Openbox icons

### ISSUE THREAD

**Issue by semeion** [johanmalm/jgmenu#69]
Hello! Congratulations for the icons feature added in openbox type menu :D It is amazing!

Anyways i think have a bug on it or i am missing something.

The icons work fine for each <item> tag in openbox menu, like this:
```<item label="Firefox" icon="/usr/share/icons/nuoveXT2/128x128/apps/firefox.png"><action name="Execute"><command>/usr/lib/firefox/firefox</command></action></item>```

BUT... it doesn´t work in <menu> tag, like this:
```<menu id="144" icon="/usr/share/icons/nuoveXT2/128x128/apps/firefox.png" label="Firefox" execute="obm-specified_bookmarks"/>```

Some workaround to solve this issue?

Thanks in advance! I love jgmenu :D

**Comment by johanmalm** [comment]
Yes. I think you’re right. I didn’t think of pipemenus. 
Should be a simple fix.
Great feedback. Thanks

**Comment by semeion** [comment]
nice

**Comment by semeion** [comment]
I am posting a pic, just for reference:  https://i.imgur.com/1XAO7sU.png

**Comment by johanmalm** [comment]
Thanks. I understand.

I’ve been preoccupied for a couple of weeks. Will soon pick it up again.

**Comment by johanmalm** [comment]
Done :smiley:
