### ISSUE TITLE
sub_hover_action for keyboard?

### ISSUE THREAD

**Issue by napcok** [johanmalm/jgmenu#74]
It is possible to configure menu to behave the same way like when you hover item with mouse, but for keyboard?
Something like:
`sub_hover_action     = 1`
but activated when you navigate with keyboard?

**Comment by johanmalm** [comment]
Thanks for writing. This has been on my mind for a while and I will take a look at it. It should be the default behaviour really.

Unfortunately it will probably not be entirely trivial. The sub-window hover related code took a while to get right. Start in hover() in jgmenu.c if you're interested in the code itself. Any change to this code need thorough testing.

I'll explore doing it without a timer to start with. Should a timer be needed, I'll want to add proper timer support first. We should use a timeout in the select() main loop really. The current setitimer() / selfpipe is okay, but doesn't scale well and was a bit of laziness on my part at the time.

**Comment by johanmalm** [comment]
@napcok Sorry - don't like to turn down requests, but I don't think I'll realistically implement this one. 

https://jgmenu.github.io/roadmap.html#unlikely
