### ISSUE TITLE
Display icons in pipe-menus (edited)

### ISSUE THREAD

**Issue by semeion** [johanmalm/jgmenu#75]
Hello,

The icons in main menu are ok, but when the dynamic ob menu is placed in a sub-menu (or something like that), the icons isn´t displayed.

https://i.imgur.com/0Icv83d.png

The code used to build above sub-menu is a perl script:

```
#!/bin/sh
#
# Script: ~/bin/obm-services
# Ver: 1.0
# Requires:
# license: GPL
# Author: Alexandre Bolelli Soares
# Last modification: 21/06/2015
#

services=(ntpd ntpdate dhcpcd wired-static-ip setkeycodes polkit bitlbee iptables avahi-daemon avahi-dnsconfd netfs samba sshd httpd mysqld lighttpd nginx fcgiwrap fcgiwrap.socket php-fpm xmr-stak)
services_files=(/etc/ntp.conf /etc/dhcpcd.conf /usr/lib/systemd/system/ntpdate.service /etc/systemd/system/ntp-once.service
                /etc/systemd/system/wired-static-ip.service /etc/systemd/system/setkeycodes.service /etc/bitlbee/bitlbee.conf
                /etc/conf.d/iptables /etc/iptables/iptables.rules
                /etc/httpd/conf/httpd.conf /etc/mysql/my.cnf /etc/samba/smb.conf /etc/ssh/ssh_config /etc/ssh/sshd_config
                /etc/lighttpd/lighttpd.conf /etc/lighttpd/conf.d/cgi.conf
                /etc/nginx/nginx.conf /etc/systemd/system/fcgiwrap.service /etc/php/php.ini /etc/php/conf.d/zend_debugger.ini /etc/php/conf.d/xdebug.ini /etc/php/php-fpm.conf)

echo "<openbox_pipe_menu>"
echo "    <separator label=\"Services\" />"
for file in "${services[@]}"; do
    if [[ "$file" == "-" ]]; then
        echo "<separator/>"
    fi
    status=$(systemctl is-enabled "$file")
    if [[ "$status" == "indirect" ]]; then
        pidof "$file" >/dev/null && status='enabled' || status='disabled'
    fi
    if [[ "$status" == "enabled" ]]; then
        echo "<item label=\"Disable $file\" icon=\"/usr/share/icons/gnome/16x16/actions/stop.png\"><action name=\"Execute\"><command>sudo -A sh -c 'systemctl stop $file;systemctl disable $file'</command></action></item>"
    elif [[ "$status" == "disabled" ]]; then
        echo "<item label=\"Enable $file\" icon=\"/usr/share/icons/gnome/16x16/actions/player_play.png\"><action name=\"Execute\"><command>sudo -A sh -c 'systemctl start $file;systemctl enable $file'</command></action></item>"
    fi
done
echo "    <separator label=\"Edit\" />"
for file in "${services_files[@]}"; do
    if [[ "$file" == "-" ]]; then
        echo "<separator/>"
    fi
    if [[ -e "$file" ]]; then
        if [[ -w "$file" ]]; then
            echo "<item label=\"$file\"><action name=\"Execute\"><command>$EDITOR $file</command></action></item>"
        else
            echo "<item label=\"$file\"><action name=\"Execute\"><command>sudo -A $EDITOR $file</command></action></item>"
        fi
    fi
done
echo "</openbox_pipe_menu>"
```

The above script is an old sub-menu and work fine in openbox, but not in jgmenu.

The icons /usr/share/icons/gnome/16x16/actions/player_play.png and /usr/share/icons/gnome/16x16/actions/stop.png used in the script need exist to be displayed. It can be modified.

Thanks for jgmenu, amazing work :D

**Comment by johanmalm** [comment]
It looks like the 'ob' module is working correctly now with respect to icons.

jgmenu itself does not show icons in pipe menus yet. This is not a bug, it's just a feature not yet implemented. It's on the [Wiki Roadmap](https://github.com/johanmalm/jgmenu/wiki/Roadmap#new-features-12-24-months).

The icon code is written for speed and efficiency. The main loop kicks off two threads to load icons,
	- the first for the root menu;
	- the second for the rest (this one starts when the first is finished.)
This allows the root-menu to be displayed quickly whilst the rest is loaded in
the background. When jgmenu is first run, icon 'cache' is created at '~/.cache/jgmenu/icons/'.
The cache consists of symlinks pointing to icons which match the name, size and
theme. On subsequence runs, icon.c reads the symlinks, thus avoiding expensive
operations searching for icons.

I will get to it at some point, but it's not been a high priority for me so far.

**Comment by johanmalm** [comment]
@semeion I'm trying to get a bit more organized with the issues. Having reviewed the 'roadmap' I think this one is unlikely to get done - it just takes us a step more complicated than I want to go.

[https://jgmenu.github.io/roadmap.html#unlikely](https://jgmenu.github.io/roadmap.html#unlikely)

Sorry. Don't like to turn down requests - but just want to give realistic feedback.
