### ISSUE TITLE
ob menu: BL "places" pipemenu: crashes if directory name has spaces

### ISSUE THREAD

**Issue by johnraff** [johanmalm/jgmenu#76]
There seems to be an escaping issue with the BunsenLabs "places" pipemenu when invoked by jgmenu's ob mode. Attempting to open any directory with a space in its name causes the menu to crash.

When invoked in Openbox's native menu, the same pipemenu opens such directories without problems. 

If called directly in a terminal bl-places-pipemenu outputs xml which looks OK.

**Comment by johanmalm** [comment]
Good catch. Yes, I could easily reproduce that. Not sure when I never thought of doing tests of filenames with spaces.

Changing the `--cmd='%s'` quotes to double-quotes in jgmenu-ob.c fixes it.

Old output:
`b c d e,^pipe(jgmenu_run ob --cmd=''/usr/bin/bl-places-pipemenu' '/home/johan/hack/b c d e'' --tag='b c d e')`

New output:
`b c d e,^pipe(jgmenu_run ob --cmd="'/usr/bin/bl-places-pipemenu' '/home/johan/hack/b c d e'" --tag="b c d e")`

I will push the change.

**Comment by johanmalm** [comment]
Fixed, I believe.
