### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jubalh** [johanmalm/jgmenu#78]
Please have a Changelog or News file.
Packagers would like to know what changed and also should include this in their package.

**Comment by johanmalm** [comment]
We put release notes in docs/release notes, for example

https://github.com/johanmalm/jgmenu/blob/master/docs/relnotes/1.6.txt

Also, on the wiki Roadmap, we tick items as we go.

Appreciate any thoughts on how to improve comms/visibility of this.

**Comment by jubalh** [comment]
Thanks for pointing me to this.

Traditionally many [projects](https://www.gnu.org/prep/standards/html_node/Change-Logs.html) tend to use a file called `CHANGELOG` or `NEWS` in the root folder. 
But now that you pointed me to your file I'll use this :)

**Comment by jubalh** [comment]
> I took the structure from the 'git' repo itself
https://github.com/git/git/tree/master/Documentation/RelNotes

Interesting! Was not aware of this.
