### ISSUE TITLE
packaging: debian/{compat,control} different debhelper versions

### ISSUE THREAD

**Issue by johnraff** [johanmalm/jgmenu#79]
debian/compat declares debhelper level 10, but in debian/control one of the Build-Depends is debhelper (>= 9)

I would suggest raising the debhelper version required in d/c to >=10 which is already available in Debian Stretch.

EDIT: Maybe also bump the year to 2019 in debian/copyright?

**Comment by johanmalm** [comment]
Thanks. Will implement.

**Comment by johanmalm** [comment]
Done
