### ISSUE TITLE
[Feature Request] Launchpad Repository

### ISSUE THREAD

**Issue by zero77** [johanmalm/jgmenu#80]
Can you please provide a Launchpad repository, for Linux distributions that dont have jgmenu in their repository.
I am using Ubuntu 18.04 and i can only install jgmenu by git clone, i think this is also the same for debian. 
Thanks

**Comment by johanmalm** [comment]
I'm quite poor at packaging and live in the hope that others will lead on that.
Having said that, it does seem a reasonable request, so I will research and take a view.

**Comment by zero77** [comment]
@johanmalm 
> I'm quite poor at packaging and live in the hope that others will lead on that.

Same here, i am also not good at packaging.
> Having said that, it does seem a reasonable request, so I will research and take a view.

Thanks

I think the best way to go would be to use Travis CI to build the deb and then automatically upload it to Launchpad.

From researching, this is what i have found so far.
Building debs From Source:
https://www.ostechnix.com/build-packages-source-using-checkinstall

Uploading from Travis CI:
https://www.gdevnet.com/use-launchpad-to-distribute-debian-packages
https://docs.travis-ci.com/user/deployment/launchpad

**Comment by zero77** [comment]
@johanmalm 
This PR builds a deb using Travis CI and it should upload it to git after.
This Issue is mostly complete the only thing left is to automatically upload the deb to a Launchpad repository.

See PR: https://github.com/johanmalm/jgmenu/pull/81

**Comment by johanmalm** [comment]
Thanks for your PR.

I'll try the launchpad instructions before deciding.
https://docs.travis-ci.com/user/deployment/launchpad/

**Comment by Vladimir-csp** [comment]
JFYI https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882210

**Comment by johanmalm** [comment]
@Vladimir-csp  thanks
@zero77  Sorry - I think I'll give up with the launchpad repo. Packaging isn't really me. Appreciate any  help with it :smile:
Will close.
