### ISSUE TITLE
Musl compatibility

### ISSUE THREAD

**Issue by Chocimier** [johanmalm/jgmenu#82]
Hello, in Void Linux we use a [patch](https://github.com/void-linux/void-packages/blob/master/srcpkgs/jgmenu/patches/musl.patch) to make jgmenu compile with musl c library. Could you merge it?

**Comment by johanmalm** [comment]
Thanks for reporting.

I added another time.h a couple of days ago for nanosleep. Have added sys/time.h for that one too.
