### ISSUE TITLE
Item not sorted

### ISSUE THREAD

**Issue by queenmedley** [johanmalm/jgmenu#83]
jgmenu version is 1.6-1 on Archlinux, openbox.
Items are not sorted by category but appear in "other dir ".

https://drive.google.com/file/d/19RmCUHJQ2_WS84-GKOiRJ7sBgnURdWVc/view?usp=sharing

**Comment by johanmalm** [comment]
Have you installed a menu package?

Try lxmenu-data

**Comment by queenmedley** [comment]
Oh~ lxmenu-data was not installed.
I've just installled it and it's fine. thanks.

**Comment by johanmalm** [comment]
That’s good. 
I’ll close.
