### ISSUE TITLE
[Feature Request] Support overriding .desktop files

### ISSUE THREAD

**Issue by Teklad** [johanmalm/jgmenu#86]
A fairly common feature across quite a few different menus I've tried (xfce, openbox w/ obmenu-generator, etc.) is being able to override .desktop files in /usr/share/applications and /usr/local/share/applications.

This is typically done by placing a .desktop file of the same name in ~/.local/share/applications and changing the configuration to your liking.  This is especially useful for hiding applications you don't want to appear in the menu via "NoDisplay=true" or changing the icon to something you feel is more suitable.

The current behavior just places a duplicate entry in the menu, at least based on what I've tested.

**Comment by johanmalm** [comment]
The 'lx' module does what you described (set `csv_cmd = lx` in jgmenurc)

The pmenu module does not support this. I could extend this script, but find it difficult to maintain, so am re-writing it in C. See yesterdays commit (534375a2)

**Comment by Teklad** [comment]
Ah okay. So the pmenu module is just a script? I didn't have very much time
to skim over the code so I wasn't sure how everything worked quite yet.

**Comment by johanmalm** [comment]
Yes

[https://github.com/johanmalm/jgmenu/blob/master/src/jgmenu-pmenu.py](https://github.com/johanmalm/jgmenu/blob/master/src/jgmenu-pmenu.py)

**Comment by johanmalm** [comment]
It should work with pmenu too now.
