### ISSUE TITLE
[Bug] Not Closing In i3

### ISSUE THREAD

**Issue by zero77** [johanmalm/jgmenu#87]
I have added jgmenu in i3 using both `'bindsym $mod+Shift+d exec jgmenu --at-pointer` and https://github.com/johanmalm/jgmenu/wiki/WM-integration.

It works but it only seems to work once, i think it's because when you click out of jgmenu
 or the application you selected has launched jgmenu
 is still open in the back ground and it stops a second one being opened.

OS:ubuntu 18.04
jgmenu:v2.2.1-10-g6bc9
i3:4.16-110-gfeb2912e

**Comment by johanmalm** [comment]
Use have two options:

(a) use jgmenu_run to launch and set at_pointer=1 in jgmenurc

(b) or use —simple to launch a short lived instance

**Comment by zero77** [comment]
@johanmalm 
> (b) or use —simple to launch a short lived instance

Is there any documentation on this.

**Comment by johanmalm** [comment]
Yes.

See the man pages jgmenu(1) and jgmenututorial(7)

In the tutorial, it’s covered in lessons 1,2 and 3.

https://github.com/johanmalm/jgmenu/blob/master/docs/manual/jgmenututorial.7.md

Personally, I prefer to use jgmenu_run and do all configuration in jgmenurc config file.

Do say if I can make the man pages or wiki clearer. I want jgmenu to be easy to get started with.

**Comment by johanmalm** [comment]
I’ve updated the wiki page.

**Comment by zero77** [comment]
Thanks
> Do say if I can make the man pages or wiki clearer. I want jgmenu to be easy to get started with.

It looks very detailed which is good but, is there info on all the configs or have i just missed that.

**Comment by zero77** [comment]
> Personally, I prefer to use jgmenu_run and do all configuration in jgmenurc config file.
> (a) use jgmenu_run to launch and set at_pointer=1 in jgmenurc

Thanks, i think this has fixed it also, it may be worth mentioning in the wiki that i3 needs jgmenu_run and not jgmenu.

**Comment by johanmalm** [comment]
@zero77 

Find 'configs' in jgmenu(1)

[https://github.com/johanmalm/jgmenu/blob/master/docs/manual/jgmenu.1.md#configuration-file](https://github.com/johanmalm/jgmenu/blob/master/docs/manual/jgmenu.1.md#configuration-file)

I've updated the wiki page.
