### ISSUE TITLE
Badness in build_tree() at src/jgmenu.c:1142

### ISSUE THREAD

**Issue by SpaceboyRoss01** [johanmalm/jgmenu#88]
Command used: `jgmenu --simple --config-file=/etc/xdg/kdux/jgmenu/jgmenurc < /etc/xdg/kdux/jgmenu/append.csv`

append.csv:
```
@rect,,23,10,454,35,3,left,top,#111111 90,#000000 0,
@search,,30,15,454,25,3,left,top,#ffffff 100,#222222 3,Type to search...
```

Output:
```
info: using monitor '1'
info: got font from jgmenurc
info: set font to 'DejaVuSansMono Nerd Font 9'
info: got icon theme from gtk config file
info: set icon theme to 'Paper'
Badness in build_tree() at src/jgmenu.c:1142
zsh: segmentation fault (core dumped)  jgmenu --simple --config-file=.config/jgmenu/jgmenurc < 
```

**Comment by johanmalm** [comment]
With ‘—simple’, menu items are read from stdin (like dmenu).

Your append.csv only contains two ‘widget’ lines.

Try adding some lines without @. For example:

firefox
xterm

I’ll look at handling this more gracefully.

**Comment by johanmalm** [comment]
We now check that at least one menu item has been supplied before trying to build the menu. Thanks for catching this short-coming.

I will close the issue, but please feel free to re-open/respond if you want to discuss further.
