### ISSUE TITLE
--config-file not honored

### ISSUE THREAD

**Issue by opk12** [johanmalm/jgmenu#89]
`jgmenu --config-file target` does not use `target` (and uses `.config/jgmenu/jgmenurc` if it exists). Moving `target` to `.config/jgmenu/jgmenurc` makes it work, so this is not caused by the config file contents.

`strace jgmenu --config-file target 2>output.log` prints occurrences of `.config/jgmenu/jgmenurc` in `output.log` and no occurrences of `target`, therefore access to `target` was not attempted at all.

jgmenu v2.2.1 on debian 10 buster and debian 9 stretch.

**Comment by johanmalm** [comment]
Hi

Are you using a ‘=‘ between --config-file and <filename>?

**Comment by opk12** [comment]
Yes, that's it. Sorry.
