### ISSUE TITLE
jgmenu mouse and keyboard actions should match Openbox/gtk

### ISSUE THREAD

**Issue by hhhorb** [johanmalm/jgmenu#90]
Currently, if I use the keyboard arrows in jgmenu, scrolling past the bottom menu entry does not return me to the top one, nor in reverse. This is counter to how both gtk2/gtk3/openbox menus all behave.

With mouse selection, hovering over a menu item opens a sub-menu if one is present in Openbox and gtk, not in jgmenu.

Is it possible to bring jgmenu in line with these other menus so they all behave more-or-less the same?

**Comment by hhhorb** [comment]
My error, mouse hover is more-or-less the same behavior, but keyboard input needs a little l
ove.

**Comment by johanmalm** [comment]
Hi @hhhorb 

If we take the question in two parts

(a) Goto top when scrolling past bottom, and vice versa - should be relatively easy to implement. I'll have a go at this.

(b) Opening submenu for active item when using keyboard - see issue #74 .

I've been pretty busy IRL for a while - and have been [scratching another itch](https://github.com/johanmalm/labwc/blob/master/README.md), but should soon be back on track

**Comment by johanmalm** [comment]
Regarding (a), I've a quick play with the code.
Due to the scroll and search/filter support, this is not a trivial change.
I think I prefer it as it is - but will of course reconsider if you feel strongly.

**Comment by hhhorb** [comment]
Of course I feel strongly, or I wouldn't have mentioned it! :dagger: 

Consider another drop-in menu, bl-obmenu-generator...

https://notabug.org/martix/bl-obmenu-generator

Using a keyboard, this works as expected. I don't need to learn 2 different keyboard navigations and remember which menu uses which. Get what I'm saying?

**Comment by johanmalm** [comment]
I've implemented (a)

Are you happy that we close this on and track (b) via issue #74 ?

jgmenu doesn't like being compared with <xml> tag generators - it makes him feel bruised and battered 
:face_with_head_bandage:

**Comment by hhhorb** [comment]
Lol, all good. Thanks!!!
