### ISSUE TITLE
Case-insensitive non-ASCII search

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#91]
It seems that non-english layouts make search case-sesnitive.

**Comment by johanmalm** [comment]
I’m not sure how to implement. Do you know of any libraries we could use?

**Comment by Vladimir-csp** [comment]
Since lx already depends on glib, maybe something in [this direction](https://developer.gnome.org/glib/stable/glib-Unicode-Manipulation.html#g-utf8-casefold). [This function](https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strncasecmp) is deprecated, but there are some potentially useful coments in the deprecation notice.

**Comment by johanmalm** [comment]
This might work

ftp://ftp.unicode.org/Public/UNIDATA/CaseFolding.txt

**Comment by Vladimir-csp** [comment]
Seems like a portable solution.
Just in case you missed the edit to my previous message, there is also [libutf8proc](https://github.com/JuliaStrings/utf8proc)

**Comment by johanmalm** [comment]
Looks a great option. Will investigate.

**Comment by johanmalm** [comment]
Hi
Decided to settle for glib.
I've tested on some Swedish characters, but appreciate any testing you can do.
Thanks

**Comment by Vladimir-csp** [comment]
It works!
Thanks
