### ISSUE TITLE
fails to exit when no menu item is selected

### ISSUE THREAD

**Issue by Boruch-Baum** [johanmalm/jgmenu#92]
When one presses ESC instead of selecting an menu item, `jgmenu` does not exit. In Archlabs linux, this isn't noticeable for some reason when accessing `jgmenu` only by pressing a mouse on its polybar launcher button, but when launched from a keybinding this is a serious bug because subsequent attempts to launch `jgmenu` silently fail, and it seems that the program just doesn't work. However, when making a second attempt from the command line, the response is
```
fatal: an instance of 'jgmenu' is already running
```
Killing the hung process allows `jgmenu` to work ... until the next time one presses ESC instead of selecting a menu item.

Running `jgmenu` from the command line and pressing ESC clearly shows that the process does not exit.

Until the code is fixed, a kludgey work-around is to associate the keybinding with a wrapper script one-liner `jgmenu || { pkill jgmenu && jgmenu ; }`.

The program version in the tested archlabs environment is v2.2, and in debian, using the bunsenlabs packages v3.0

**Comment by Boruch-Baum** [comment]
I see now that I was supposed to bind the key to `jgmenu_run`, not `jgmenu`, so this issue can be closed, but it might be worthwhile to make the documentation more clear about this.

**Comment by johanmalm** [comment]
Glad you solved it. I have amended man page jgmenu.1

If you set `stay_alive = 0` in ~/.config/jgmenu/jgmenurc, you can launch the menu with jgmenu as you attempted.
