### ISSUE TITLE
pmenu error

### ISSUE THREAD

**Issue by mrneilypops** [johanmalm/jgmenu#93]
Hi,
jgmenu works fine on my dwmX live cd.
I have encountered an error on dwmX after install;

`fatal: 'pmenu' is not a jgmenu_run command`

If I update jgmenu on the installed dwmX then jgmenu works again...

Until recently jgmenu has been running fine on dwmX.
I have also upgraded to jgmenu v3.2 with same error.

Any ideas most welcome as I am trying to release the final version.

https://sourceforge.net/projects/dwmx/files/
https://dwmx.org/

![dwmX-jgmenu](https://user-images.githubusercontent.com/1450448/61380764-4100f800-a8aa-11e9-93e7-38dcf47e8fa1.png)

**Comment by johanmalm** [comment]
Sounds like you’ve got jgmenu and jgmenu_run in your bin directory, but have deleted associated lib directory (where the pmenu module lives).

Have you installed to your $HOME directory and the deleted lib, but left bin?

Run jgmenu_run --exec-path to see what libexec dir we’re expecting jgmenu-pmenu.py to be in.

**Comment by mrneilypops** [comment]
This looks to me like a problem of user change after install.
jgmenu_run --exec-path gives
/home/live/lib/jgmenu
but the user is now mrneilypops.
I also found that I had installed jgmenu locally and system wide. I am compiling a new ISO with just the local config. 
Would this be the correct approach?

**Comment by johanmalm** [comment]
I think you’d be best creating a deb package and doing a system wide installation.


dpkg-buildpackage -tc -b -us -uc
sudo dpkg -i ../jgmenu_<whatever>.deb

**Comment by mrneilypops** [comment]
Hmm...hadn't considered that.
Keep you posted on a system wide install.
Will this impact my present configs in the $HOME directory?

**Comment by johanmalm** [comment]
‘make install’ copies files to bin, lib, share.

Your jgmenurc is in $HOME/.config (I assume). This directory is not touched by the the installation.

**Comment by mrneilypops** [comment]
Cheers. I will try this momentarily...

**Comment by mrneilypops** [comment]
deb installed.
I now have jgmenu in /usr/local/bin and /usr/bin 
Is thIS ok?

**Comment by johanmalm** [comment]
I think /usr/bin is best on Debian. That's what the default debian/ files are setup to do.

I'd delete all the /usr/local/ jgmenu related files. To keep the system clean, you have to delete the following:

```
/usr/local/bin/jgmenu*
/usr/local/lib/jgmenu/
/usr/local/share/man1/jgmenu*
/usr/local/share/man7/jgmenu*
```

If you all so `make prefix=$HOME uninstall`, you'll get rid of anything jgmenu related files (ex config files) in your $HOME directory.

[INSTALL.md](https://github.com/johanmalm/jgmenu/blob/master/INSTALL.md) describes some of this.

**Comment by mrneilypops** [comment]
deb installed.
/usr/local files deleted as per your advice.
`make prefix=$HOME uninstall`
new ISO compiled.
new ISO live jgmenu runs OK.
new ISO installed to VB jgmenu runs OK!!!
new ISO uploading to SF...

[I just wonder why this happened???
 jgmenu had been working fine 'in local' mode post install thus far???]

Thank you for your fast and useful advice.

**Comment by johanmalm** [comment]
Good stuff.

When you run make install, the libexec path is written to jgmenu_run, so if it’s installed in your HOME dir and the username then changes, that would cause a problem.

Anyway, glad it’s solved.

**Comment by mrneilypops** [comment]
Thanks again.
On my way to dwmX FINAL...
