### ISSUE TITLE
Can't use OpenBox keybindings while showing menu

### ISSUE THREAD

**Issue by 01885404983** [johanmalm/jgmenu#94]
When I run jgmenu, it prevents me from using OpenBox keybindings such as screen capture (Print), switch window (Alt+Tab), ... When the menu is closed everything work as usual.

I use jgmenu (v3.0.1) with OpenBox on ArchLinux. This is my jgmenurc

    stay_alive = 0
    hide_on_startup = 0
    csv_cmd = pmenu
    columns = 5
    menu_width = 1600
    menu_padding_top = 50
    item_height = 50
    csv_no_dirs = 1

**Comment by johanmalm** [comment]
Hi
That’s the way it’s designed.
It grabs the pointer and keyboard.
For screenshot, do ‘scrot -cd5’ or prepend you favourite screenshot tool with ‘sleep 5 ;’ or similar

**Comment by 01885404983** [comment]
That bit is a little annoying, but the rest is awesome, thank you for your precious work.
