### ISSUE TITLE
fatal: error setting locale

### ISSUE THREAD

**Issue by yanivkfir** [johanmalm/jgmenu#96]
jgmenu and jgmenu_run gives the error fatal: error setting locale upon launch.

locale is set to en_IL.UTF-8

**Comment by johanmalm** [comment]
I think it’s libmenu-cache giving that.

Does that locale exist?
Please show the output of

    locale -a

**Comment by yanivkfir** [comment]
yes. en_IL and en_IL.utf8 exist

**Comment by johanmalm** [comment]
Do you get the error message with

    jgmenu_run lx

**Comment by yanivkfir** [comment]
that one gives me a fatal: error setting locale error

**Comment by yanivkfir** [comment]
that one gives me a "fatal: cannot find a menu file" error

**Comment by johanmalm** [comment]
What’s the output of

    echo $LANG

What OS / distribution are you using?

**Comment by yanivkfir** [comment]
echo $LANG returns en_IL.UTF-8
using Linux Arch

**Comment by johanmalm** [comment]
Got to a computer at last.

I don't know too much about "locale", but guess that the error happens during setlocale() in init_locale() in jgmenu.c

Are you happy to build jgmenu from scratch? If so, I can give you some things to try - we could start by adding some more helpful error messages to init_locale().

setlocale() will return NULL if locale string is invalid or if the locale you want is not installed.

Does the following work?

    LANG=C jgmenu

Have you set any LC_ environment variables on your system? Check with:

    set | grep 'LC_'

Do you get any problems with any other applications?

Please could you post the output of the following commands

    locale
    locale -a
    localectl
    grep -v '^#' /etc/locale.gen

Are you running KDE by any chance? I spotted a thread on the Arch Linux forums with a 'locale issue'

**Comment by yanivkfir** [comment]
LANG=C jgmenu did work already implemented it into i3 and it seems to work perfectly well. still open to playing around with the code if you want me to test possible fixes but I think this workaround will work well.

looks like there is some LC_ eviroments, got

    LC_COLLATE=C
        local LC_CTYPE=C;
        local addrs=$({ LC_ALL=C ifconfig -a || ip addr show; } 2>/dev/null |
                local argtype=$(LC_ALL=C $1 --help 2>&1 | command sed -ne                 "s|.*$prev\[\{0,1\}=[<[]\{0,1\}\([-A-Za-z0-9_]\{1,\}\).*|\1|p");
        COMPREPLY=($(compgen -W "$(LC_ALL=C $1 --help 2>&1 |             while read -r line; do                 [[ $line =~ --[-A-Za-z0-9]+=? ]] &&                     printf '%s\n' ${BASH_REMATCH[0]}
    COMPREPLY+=($(        { LC_ALL=C ifconfig -a || ip link show; } 2>/dev/null | command sed -ne         "s/.*[[:space:]]HWaddr[[:space:]]\{1,\}\($re\)[[:space:]].*/\1/p" -ne         "s/.*[[:space:]]HWaddr[[:space:]]\{1,\}\($re\)[[:space:]]*$/\1/p" -ne         "s|.*[[:space:]]\(link/\)\{0,1\}ether[[:space:]]\{1,\}\($re\)[[:space:]].*|\2|p" -ne         "s|.*[[:space:]]\(link/\)\{0,1\}ether[[:space:]]\{1,\}\($re\)[[:space:]]*$|\2|p"
                LC_ALL=C "$(dequote "$cmd")" ${2:---help} 2>&1
                LC_ALL=C "$(dequote "$cmd")" ${2:---usage} 2>&1

I did have locale issues with dmenu about 6 months ago, [which from my understanding might be somehow related to this old bug](https://bugs.freedesktop.org/show_bug.cgi?id=106362)

locale:
```
LANG=en_IL.UTF-8
LC_CTYPE="en_IL.UTF-8"
LC_NUMERIC="en_IL.UTF-8"
LC_TIME="en_IL.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_IL.UTF-8"
LC_MESSAGES="en_IL.UTF-8"
LC_PAPER="en_IL.UTF-8"
LC_NAME="en_IL.UTF-8"
LC_ADDRESS="en_IL.UTF-8"
LC_TELEPHONE="en_IL.UTF-8"
LC_MEASUREMENT="en_IL.UTF-8"
LC_IDENTIFICATION="en_IL.UTF-8"
LC_ALL=
```
locale -a
```
C
POSIX
en_IL
en_IL.utf8
he_IL.utf8
```

localectl
```
   System Locale: LANG=en_IL.UTF-8
                  LC_COLLATE=C
       VC Keymap: us
      X11 Layout: us,il
       X11 Model: grp:alt_shift_toggle
```
grep -v '^#' /etc/locale.gen
```
en_IL UTF-8  
he_IL.UTF-8 UTF-8  
```

and I am running i3

**Comment by johanmalm** [comment]
Hi again

It looks like we should just warn on failed setlocale(LC_ALL, "") rather than die(). I have pushed a commit to this effect.

See for example [https://github.com/GNOME/gtk/blob/master/gtk/gtkmain.c#L558
](https://github.com/GNOME/gtk/blob/master/gtk/gtkmain.c#L558)

I'm not sure what the actual issue is, but am inclined to think that it's no jgmenu specific.

I'll close with this, but please do say if there is anything else you think I should do or try.
