### ISSUE TITLE
Unable to build from current "master" branch

### ISSUE THREAD

**Issue by SchweinDeBurg** [johanmalm/jgmenu#98]
```
     LINK  jgmenu-lx
     CC    libjgmenu.so
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/crt1.o: in function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:22: libjgmenu.so] Error 1
make: *** [Makefile:85: all] Error 2
error: Bad exit status from /home/elijah/.local/tmp/rpm-tmp.cGeob6 (%build)
```
Fedora 26, stock GCC 7.3.

**Comment by zvezdochiot** [comment]
```
libjgmenu.so
```
???

**Comment by SchweinDeBurg** [comment]
Yes, this is output from "rpmbuild" command. Inside the .spec file there is simple call:
```
%{__make} prefix=%{_prefix} libexecdir=%{_libdir}/%{name}
```

**Comment by SchweinDeBurg** [comment]
I've solved this error by adding  NO_XFCE_PLUGIN=1 to the make invocation.

**Comment by zvezdochiot** [comment]
Where do you see .spec file? Go to your maintainers and ask them what they got there. This is not the place here!

**Comment by johanmalm** [comment]
Apologies.

I added the new xfce4-panel-plugin to the default build, but think I’ll make it optional instead (to avoid the sort of breakage). 

The new plugin needs libgtk-3-dev and xfce4-panel-dev (or equivalent on other distributions).
