### ISSUE TITLE
Arrow color in selection doesn't match color_sel_fg value

### ISSUE THREAD

**Issue by J-MDO** [johanmalm/jgmenu#99]
It seems like the color of the submenu arrow is determined by color_norm_fg
so when selected it should match color_sel_fg value.

However It's not the case as the arrow color doesn't change when selecting a submenu element

![image](https://user-images.githubusercontent.com/54105563/66127469-09256900-e5ec-11e9-9470-b28c79a53bd5.png)
In this screenshot the arrow should be pink

Thank's for your work

**Comment by johanmalm** [comment]
Hi
Great catch. Thank you.
Now fixed.
